### ISSUE TITLE
App started to ignore system font size

### ISSUE THREAD

**Issue by CatKasha** [SimpleMobileTools/Simple-Calendar#994] opened 2019-10-12 07:09 UTC
App started to ignore system font size (the same thing happened with Simple Gallery 6.10.0 and 6.10.1)
Android: 7.1.2, system font size: small, apps from F-Droid
Calendar 6.6.2:
![Calendar 6 6 2](https://user-images.githubusercontent.com/19823797/66696766-72d20100-ecd7-11e9-9058-0fa312104a61.png)
Calendar 6.6.1:
![Calendar 6 6 1](https://user-images.githubusercontent.com/19823797/66696769-7bc2d280-ecd7-11e9-9b7a-752cbf1a31a6.png)

**Comment by tibbi** [comment] 2019-10-13 10:36
it was caused by a system library, that got updated. It will be fixed in the next app version 6.6.3 released soon.

**Closed by tibbi** 2019-10-13 10:36 UTC
Labels: bug

**Comment by CatKasha** [comment] 2019-10-13 18:27
Thanks for fixing!
