### ISSUE TITLE
New feature idea: extended support for local ics files (secure and private synchronization between multiple devices with no man-in-the-middle)

### ISSUE THREAD

**Issue by menoos** [SimpleMobileTools/Simple-Calendar#1633] opened 2022-02-08 09:19 UTC
Background:
Lately I was trying to find a solution to synchronize calendars between Android and Linux with no 3rd party servers in the middle, and didn't find any reliable ready to use tools. Though after my research I found that Evolution suite is able to not only import and export ics files, but use them as a fully functional calendars (write all modifications on the fly).
Those ics files can then be easily synced between multiple devices with for example Syncthing (or any other tools). In this case we only miss an Android calendar app that would be able to work with them the way Evolution does.

Feature description:
On top of import/export which is already implemented, it would be great if Simple-Calendar would be able to:
1. Open local ics file(s)
2. Save all modifications made to the calendar(s) on the fly
3. Watch those files for updates (changes made on other devices and synchronized with Android) and update calendar(s) accordingly.

This way you would be able to make a secure and private synchronization between multiple devices with no man-in-the-middle.

**Comment by tibbi** [comment] 2022-02-08 11:45
duplicate of #174

**Closed by tibbi** 2022-02-08 11:45 UTC
