### ISSUE TITLE
Event type incorrectly changed when editing

### ISSUE THREAD

**Issue by Phanx** [SimpleMobileTools/Simple-Calendar#571] opened 2018-08-01 03:41 UTC
**Version information:**

Simple Calendar 4.1.2 from F-Droid. At the time of writing, this is also the latest version on Google Play.

**Steps to reproduce:**

1. Have at least two event types, Green and Red.
2. Create an event Event A, with type Green. Other details do not matter.
3. Create an event Event B, with type Red. Other details do not matter.
4. Tap to edit Event A.
5. Scroll down to look at the event type. See that it still shows Green, which is what the event was created with.
6. Scroll back to the top and tap the check mark to save the event.

**Expected result:**

Event X still has the Green event type, as it was created with, as was shown in the edit page, and was not modified in the edit page.

**Actual result:**

Event Y now has the Red event type.

**Other information:**

The event type field seems to commit the last value *actively entered* in it, regardless of what it's actually displaying.

The bug can be avoided by tapping on the event type field and re-selecting the same event type that *should* already be selected, but it's easy to forget, and potentially awkward when private events end up appearing on my (shared) work calendar.

I can reproduce this consistently, and it's been happening for quite a while; I just never got around to formally testing to identify the minimum steps to reproduce until now.

**Comment by tibbi** [comment] 2018-08-05 20:52
it used to happen to me too, but I cannot reproduce it anymore as it should be fixed already. Can you reproduce it with newly created events? Do you have CalDAV sync enabled?

**Comment by Tavlor** [comment] 2018-08-09 23:09
I reproduced this just now using v 4.1.3; it specifically affects CalDAV calendars; not local calendars:
1. Create event A (CalDAV event), event B (CalDAV event on another calendar), and  event 1 (local event) 
2. Edit event A (open editor and save)
3. (optional) Edit event 1. The event stays keeps it's type.
4. Edit event B. On saving, event B is moved to event A's calendar.

The change will keep happening as other CalDAV events are edited regardless of what calendar they originally are in. My tests were all in one CalDAV account; I don't know if the changes will happen across accounts.

**Comment by Phanx** [comment] 2018-08-19 20:29
It does happen across accounts; I mainly use several calendars created using the Local Calendar app (local-only calendars, but integrated with the Android calendar system so they're available to any calendar app, and Simple Calendar reads these via CalDAV sync) but also have two Google accounts with calendars synced, one personal (almost never used) and one for work (frequently used). I've definitely had events get switched from "personal Local Calendar" to "work Google" or vice versa.

**Comment by tibbi** [comment] 2018-09-25 12:02
according to a reporter it still happens

**Comment by tibbi** [comment] 2018-10-24 16:30
it should be fixed in 5.0.2. If it still wont be, tell me the exact steps for reproducing the issue.

**Closed** 2018-10-24 16:29 UTC
Labels: bug
