### ISSUE TITLE
How-to OR feature request: automate export

### ISSUE THREAD

**Issue by SvV-CWin** [SimpleMobileTools/Simple-Calendar#873] opened 2019-05-03 16:19 UTC
Hi,

Thank you for developing these apps. I use the calendar app as my standard.

I would like to be able to do the export to *.ics by command (that is, without user interaction). Is there a way to communicate with calendar to achieve this? I use the Automate app for a lot of automation (it can handle intents, broadcasts,...)

Regards, 
Sven

**Comment by tibbi** [comment] 2019-05-03 16:47
there is no way for now, duplicate of #174

**Closed by tibbi** 2019-05-03 16:47 UTC

**Comment by iammexan** [comment] 2019-12-16 12:09
Hey dev, check out this app called [Tasks](https://github.com/tasks/tasks) 

I'm using this app for quite some time and noticed it has the feature of [automatic backup generation](https://tasks.org/docs/backups.html). Every night at 12 o'clock  this app generates and saves a json file of all my tasks to a chosen file folder ( I chose sd card ). 

Can we please get this feature in Simple Calendar? It's a very important feature.

**Comment by tibbi** [comment] 2019-12-16 12:15
it is on the roadmap, but I cannot promise any date yet
