### ISSUE TITLE
Feature Request: Add a weekly view widget

### ISSUE THREAD

**Issue by dwettstein** [SimpleMobileTools/Simple-Calendar#1920] opened 2023-01-03 15:23 UTC

**Comment by tibbi** [comment] 2023-01-03 16:17
duplicate of #488

**Closed by tibbi** 2023-01-03 16:17 UTC

**Comment by dwettstein** [comment] 2023-01-03 19:15
This is not really a duplicate of #488. This request here is about having a (1) week widget similar to the weekly view, not a customized month widget showing multi weeks.

**Comment by Aga-C** [comment] 2023-01-03 19:46
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/398.
