### ISSUE TITLE
Feature Request: Allow Recurring/Repeating Alarm per calendar entry

### ISSUE THREAD

**Issue by CrateDepth** [SimpleMobileTools/Simple-Calendar#2039] opened 2023-04-04 19:28 UTC
Simple Mobile Calendar allows easy overview (e.g. month view, week view, etc...) of recurring events/tasks, just like any other digital calendar (Outlook, Google Calendar). I add tasks which must be finished by the end of the day but which there is no fixed time to it (i.e. it is an important but not 'urgent' task). Currently, I do this by adding an all day task for a particular day (at midnight) and set reminders x hours before the midnight.

What I have found is that I am usually busy with other physical tasks when I hear the notification alarm. Therefore, I cannot look at my mobile device to dismiss the alarm or even view what the task is of which I am being notified of. I miss or forget the notifications despite the 3x reminders.

Would it be possible, in addition to the 3x reminders, to have a recurring/repeating reminder option in a event/task where the user can set the amount of time between notification alarms? The alarms would keep on recurring/repeating until the user dismisses them.

**Comment by Aga-C** [comment] 2023-04-04 19:49
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1082.

**Closed** 2023-04-05 06:37 UTC
