### ISSUE TITLE
[Feature Request] Change accent color of date and time selection pop-up

### ISSUE THREAD

**Issue by libalis** [SimpleMobileTools/Simple-Calendar#1216] opened 2020-10-13 23:38 UTC
It would be amazing if the date and time picker pop-up accent color was synced with the application's accent color, or if it could be changed individually.
From what I've seen, this seems to be the last unchangeable color in the otherwise fully customizable app.
Also, I just wanted to say what a great job you are doing and how much I love your philosophy and programs.

**Comment by tibbi** [comment] 2020-10-14 22:13
those dialogs come from the system, arent created by us. Thats why they are hard to customize, we can just toggle light/dark mode

**Comment by libalis** [comment] 2020-12-06 13:02
Please excuse me for the late reply.
But is there really no way to overwrite it?

**Comment by tibbi** [comment] 2020-12-06 14:30
There surely are some ways, but Android doesn't support any easy and reliable way for it

**Comment by tibbi** [comment] 2021-03-10 18:09
Ill close it as a duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/146 as it affects multiple apps

**Closed by tibbi** 2021-03-10 18:09 UTC
Labels: feature request
