### ISSUE TITLE
Fit weekly view into page

### ISSUE THREAD

**Issue by sledz** [SimpleMobileTools/Simple-Calendar#520] opened 2018-06-08 13:45 UTC
On the screens of the usual Android devices (smartphone, tablet) it is practically always necessary to scroll vertically in the weekly view to see all times.

It would be very helpful to shrink this view vertically so that it fits exactly into the existing height.

**Comment by tibbi** [comment] 2018-06-08 16:02
duplicate of #218

**Closed by tibbi** 2018-06-08 16:02 UTC
Labels: feature request
