### ISSUE TITLE
Do not show toast of exception

### ISSUE THREAD

**Issue by BuZZ-dEE** [SimpleMobileTools/Simple-Calendar#1374] opened 2021-05-13 18:55 UTC
Please do not show a toast with an exception that does need a long time to disappear. It blocks the screen, so I can not see for example my keyboard.

**Comment by tibbi** [comment] 2021-05-13 19:14
what toast you mean?

**Comment by BuZZ-dEE** [comment] 2021-05-13 19:25
![Screenshot_20210513-205020](https://user-images.githubusercontent.com/125954/118176430-b2237f00-b431-11eb-8251-bab7cf09cb61.jpg)

**Comment by tibbi** [comment] 2021-05-13 19:37
well that is a separate issue, the toast has a reason. Duplicate of #1037

**Closed by tibbi** 2021-05-13 19:37 UTC
