### ISSUE TITLE
Provide notifications for events with no reminders

### ISSUE THREAD

**Issue by advait404** [SimpleMobileTools/Simple-Calendar#2108] opened 2023-06-08 01:03 UTC
Hi, sometimes when events are imported from other sources, the reminder section for them is empty. It causes no notifications to be triggered unless the entry is manually edited. This can be a pretty bad user experience, as one would expect to have reminders for all events by default.

The app https://github.com/quarck/Calendar Notification from fdroid has this functionality to notify about events with no reminder added. I think this can be a very useful feature for simple calendar.

For my current usecase, I sign up for a lot of webinars, which by default add an event to the outlook calendar, but do not come with a reminder. This can causes me to miss the event.

**Comment by Aga-C** [comment] 2023-06-08 04:40
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1000.

**Closed** 2023-06-08 04:41 UTC
