### ISSUE TITLE
[feature request] widget font size setting

### ISSUE THREAD

**Issue by kubuntu-newbie** [SimpleMobileTools/Simple-Calendar#2114] opened 2023-06-13 17:06 UTC
could you please add a setting for font size used in widgets? current font used in the events list widget is significantly larger than the system font making it look out of place / stand out on the screen. it would be great to be able to change that font size via settings in the app

**Comment by Aga-C** [comment] 2023-06-13 18:06
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1514.

**Closed** 2023-06-14 06:41 UTC
