### ISSUE TITLE
Months scroll vertically (continuous) instead of horizontally [Feature Request]

### ISSUE THREAD

**Issue by deeeseee** [SimpleMobileTools/Simple-Calendar#2124] opened 2023-06-21 19:04 UTC
I love the Simple Calendar Pro app! Thank you for all your hard work on this app!
I'd like to request a change/improvement where the months of the calendar scroll vertically instead of horizontally (in monthly view).

Maybe there could be a setting where the vertical scrolling 'snaps' from month to month (like it does currently when scrolling horizontally), or maybe it would scroll continuously where you can view the end of one month and the beginning of the next month, at the same time. Continuous scrolling would really help view events that happen to overlap months.

With continuous scrolling, there could also be an option to show today's date either at the top of the screen, or in the middle of the screen. Currently, at the end of each month, today's date is at the bottom of the screen, so I cannot see future events in the following 2 weeks.

One disdvantage of vertical scrolling is that the "pull-down to refresh" feature would have to be modified somehow, but I hardly ever use the "pull-down to refresh" feature.

**Comment by tibbi** [comment] 2023-06-21 19:45
duplicate of #196

**Closed by tibbi** 2023-06-21 19:45 UTC
