### ISSUE TITLE
CalDAV sync is broken

### ISSUE THREAD

**Issue by KonomiKitten** [SimpleMobileTools/Simple-Calendar#269] opened 2017-11-08 02:56 UTC
After updating from 2.9.2 to 2.10.0 I can no longer select any calendars with CalDAV, it just simply lists none. Reverting to 2.9.2 fixes this issue, please see screen shot below of 2.10.0 failing to find any calenders.

![screenshot_20171108-135405](https://user-images.githubusercontent.com/12713710/32529414-95bdd11e-c48c-11e7-8699-291a2a0084e0.png)

**Comment by mdkuser** [comment] 2017-11-08 07:35
I can confirm this issue: Upgrading to 2.10.0 results in an empty clendar dialog when trying to select the dav calendars. If you close this dialog there the option to select calendars is missing from the settings menu.
Downgrading to 2.9.2 fixes the issue.

**Closed** 2017-11-08 08:07 UTC
Labels: bug

**Comment by Zero3** [comment] 2017-11-12 16:24
@tibbi I'm seeing this issue on version 2.10.1 where I think this is supposed to be fixed. I can see my CalDAV calendars (synced with the CalDAV-Sync app) through the stock calendar app just fine.

**Comment by tibbi** [comment] 2017-11-12 18:02
Can you please try finding the app in your device settings and doing a "Clear Data"? That will reset everything, also remove your events and settings, so make some backup if worth it.

**Comment by Zero3** [comment] 2017-11-12 19:10
@tibbi Tried both that and reinstalling. Still does not work :(.

**Comment by tibbi** [comment] 2017-11-12 19:12
Was it working before? What Android version do you have? If it is 6+, did you get asked the Calendar permission at toggling CalDAV sync for the first time?

**Comment by Zero3** [comment] 2017-11-12 19:21
@tibbi I'm a first time user, so I can't tell. Android 8.0.0 on a Google Nexus 6P. Was asked for the permission and gave it.

**Comment by tibbi** [comment] 2017-11-12 20:12
Ok, weird. I dont have an Android 8 (not sure if it is related), so if you can shoot me an email at hello@simplemobiletools.com please, that way I can easily send you some test versions to try finding out where does it get stuck. Thanks

**Comment by mdkuser** [comment] 2017-11-13 08:41
If downgrading to 2.9.2, does it works then for your, or do you still dont't see any calendars in the list?

**Comment by tibbi** [comment] 2017-11-13 09:40
Most likely ive found the issue already, Ill just try fixing a couple more things and releasing a new version today.

**Comment by Zero3** [comment] 2017-11-13 09:42
@mdkuser I gave it a try without any luck. No calendars are shown in the popup using either version. Maybe this is a different issue than originally reported after all?

I already received some debug builds from @tibbi, and ended up discovering a `SecurityException` about missing calendar permissions. I think he is looking into it at the moment.

**Comment by tibbi** [comment] 2017-11-13 09:45
@Zero3 I sent you a new build like 10 minutes ago, test it please.

**Comment by SamWhited** [comment] 2017-12-20 17:32
I am seeing the same behavior using v3.0.1 from the play store. Can this issue be reexamined please? Thank you.

**Comment by tibbi** [comment] 2017-12-20 17:52
Hm, the app has been updated 2 weeks ago, so far nobody reported such issue. It was related to a removed permission from the manifest, I havent touched it since then. Do you want to sync with your Google account, or some other one? Simple Calendar doesnt contain a sync adapter yet, so you might need some third party "CalDAV sync adapter" to see proper calendars and events. Google Calendar handles the sync of Google accounts, for others you might need aCalDav or some alternative. THanks

**Comment by SamWhited** [comment] 2017-12-20 18:00
Oh, does this setting only apply to Google accounts? I am trying to sync a calendar from fastmail. The settings option just said "caldav sync" so I assumed that when I clicked it it would allow me to enter a URL. Maybe this is a UI/documentation issue then, or did I misunderstand?

**Comment by tibbi** [comment] 2017-12-20 18:07
It's not only for Google Accounts, it works for others too. But your device has to be aware of other calendars first, does the sync maybe work in other apps on your device? To handle the sync between fastmail and your device, there has to be some sync adapter. For now it has to be some third party app, Simple Calendar isn't capable of that. This thread might have a bit more info https://github.com/SimpleMobileTools/Simple-Calendar/issues/259

**Comment by SamWhited** [comment] 2017-12-20 18:11
I tried acaldav and that worked for me; thanks! It just wasn't obvious to me that it needed a third party app to work from the way the widget shows up in settings. Thanks again!

**Comment by Zero3** [comment] 2017-12-20 18:56
@SamWhited I'm currently using [DAVdroid](https://play.google.com/store/apps/details?id=at.bitfire.davdroid) which have been working reasonably well for me so far.

**Comment by fuerbringer** [comment] 2018-04-22 16:48
I'm having the exact same issue as KonomiKitten except with v 3.4.2. DAVdroid is running in the background just fine with every possible permission granted to both applications.

**Comment by tibbi** [comment] 2018-04-22 17:15
do you see the proper calendars in some other calendar apps?

**Comment by fuerbringer** [comment] 2018-04-22 18:35
@tibbi I've tried three Android client applications in total, none of which seemed to detect the calendar DAVdroid had synchronized locally (see [screenshot](https://0x0.st/sQHg.jpg)). I've update both Simple Calendar and DAVdroid to their latest F-Droid versions. Again, I've also tried clearing all possible caches and giving permissions on both sides, but with no success. Mozilla Thunderbird on the other hand works fine on Desktop.

**Comment by tibbi** [comment] 2018-04-22 18:48
not sure what is the issue there, but it seems like a DAVDroid problem there. Dont you have a rooted device or some apps related to extra security? Those could be causing some issues.

**Comment by fuerbringer** [comment] 2018-04-22 19:13
@tibbi That fixed the issue I had. Hadn't realized shares are only available upon checking that box in DAVdroid. Either me not paying attention or lacking UX in DAVdroid. Thanks!

**Comment by tibbi** [comment] 2018-04-22 19:33
heh ye, bad UX in apps is one of the reasons these apps have been created in the first place

**Comment by 0pLuS0** [comment] 2019-02-13 07:39
I only have SimpleCalendar installed and using DAVx5 with Gmail account, when I tap to enable CalDav sync I am getting the same popup message;

```Select Calendars to sync```

**Comment by 0pLuS0** [comment] 2019-02-13 07:40
@tibbi 

I only have SimpleCalendar installed and using DAVx5 with Gmail account, when I tap to enable CalDav sync I am getting the same popup message;

```Select Calendars to sync```

Isn't Simple Calendar suppose to see my CalDAV with DAVx5?

Thanks

**Comment by tibbi** [comment] 2019-02-13 09:13
So you dont see any calendars for syncing there? Do other calendar apps work better?

**Comment by 0pLuS0** [comment] 2019-02-13 23:23
@tibbi maybe there's an order to this that helps, like installing SimpleGallery first, then DAVx5, because I assumed that after the accounts were added into DAVx5, that it would then sync and Simple Gallery would notice the account, at least I thought this is how I did this.

So, after playing around I realized that when I went into DAVx5 and synced the account, at that point Simple Gallery saw the account.

So no matter how someone goes about this, if you hear of it again, I suggest people go into DAVx5 and sync their account and try again...

Thanks for your reply...
