### ISSUE TITLE
widget not updating calender highlighted day

### ISSUE THREAD

**Issue by nutpantz** [SimpleMobileTools/Simple-Calendar#2013] opened 2023-03-20 03:54 UTC
With one on the latest updates, my widget of the calender is no longer updating the highlighted date for today. Now every day i have to go into the app for the widget to update. Never had to before.
Latest fdroid version.

**Comment by Aga-C** [comment] 2023-03-20 07:24
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/590 and https://github.com/SimpleMobileTools/Simple-Calendar/issues/1231.

**Closed** 2023-03-20 10:12 UTC
