### ISSUE TITLE
Shift in calendar appointments when travelling to other time zones

### ISSUE THREAD

**Issue by Aiurek** [SimpleMobileTools/Simple-Calendar#1466] opened 2021-09-07 15:47 UTC
Lenovo Moto G4 plus, Android 7.0
Simple-Calendar v6.15.1 Pro

I'm really struggling with shifts of appointments/birthdays in my calendar, when I'm using the calendar somewhere abroad. Even if it's only a -6 h time zone (compared to the one I've set all my calendar appointments), all the appointments get shifted forward by an entire day, i.e. if there's a birthday or appointment planned for the 10th it shows up on the 9th when I'm abroad which is extremely confusing :/

I know I can alter the time zone for individual appointments, but for re-occurring events like birthdays (all-day events) this wouldn't make too much sense. 

Feels like a bug somehow... whereby as far as I know even the g-calendar is shifting dates when changing the time zones. But should this already occur after a minor -6 h time shift?

Apart from that everything is great! Thank you and keep up the good work! ;)

**Comment by tibbi** [comment] 2021-09-07 17:51
Right, time zone handling needs some improvements, not yet sure when will it work as expected. Anyway, Ill close it as a duplicate of #1256 to have such time zone issues grouped there.

**Closed by tibbi** 2021-09-07 17:51 UTC
