### ISSUE TITLE
Improvement: Word wrap in the title of the event (event settings)

### ISSUE THREAD

**Issue by Moostek** [SimpleMobileTools/Simple-Calendar#1964] opened 2023-01-30 22:41 UTC
Hello, i face one problem with the event title. I create many times long titles of events, and when i click on the detail of the event (settings of the event), I do not see whole textation of the title, I have to scroll with the keyboard on the end, and it takes time. So, can you fix it with a simple act called **word wrap**? Such title will be on two (three, etc.) lines and i will see it all on the first sight.

**Comment by Aga-C** [comment] 2023-01-31 08:17
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1748.

**Closed** 2023-01-31 09:12 UTC
Labels: feature request
