### ISSUE TITLE
[Feature Request] Setting Reminder by Event Type

### ISSUE THREAD

**Issue by uinversion** [SimpleMobileTools/Simple-Calendar#1492] opened 2021-10-09 15:13 UTC
Would it be possible to add a feature to specify the kind of reminder I need, depending on the event type. For example, suppose I have some less important events in event type A, and important meetings in event type B. It would be nice to specify a default reminder for both events. For eg:

For event A: reminder 15 minutes before
For event B: reminder 1 day before, 1 hour before, 5 mins before

Thank you

**Comment by tibbi** [comment] 2021-10-09 15:22
some templates might be added in the future, duplicate of #566

**Closed by tibbi** 2021-10-09 15:22 UTC
