### ISSUE TITLE
Feature request : Ability to set reminders at some time of the day

### ISSUE THREAD

**Issue by TNZ9** [SimpleMobileTools/Simple-Calendar#2102] opened 2023-06-04 10:38 UTC
I'm running the latest release (6.21.9)
To my knowledge, it's only possible to set reminders x time before the event, it's useful but it would be cool to be able to set a reminder like "x days before at xx:xx" or "the day of the event at xx:xx" because it can be bothering to calculate the amount of time between the moment I want to have a reminder and the moment of the event

**Comment by Aga-C** [comment] 2023-06-04 14:12
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1911.

**Closed** 2023-06-05 08:18 UTC
