### ISSUE TITLE
week view broken on re-open sometimes

### ISSUE THREAD

**Issue by duchampdev** [SimpleMobileTools/Simple-Calendar#675] opened 2018-10-24 16:33 UTC
From time to time, if I re-open the app to week view after a longer time, the header (dates and weekdays) is missing.
Do you know a quick fix for that? Otherwise I could also have a look into it and try to fix it by myself.

**Comment by tibbi** [comment] 2018-10-24 16:34
Im not sure what is wrong there, I plan taking a look at it soon, maybe even today. Duplicate of #359

**Comment by duchampdev** [comment] 2018-10-24 16:35
Sorry, didn't find the old one. Thank's a lot!

**Closed by tibbi** 2018-10-24 16:34 UTC
