### ISSUE TITLE
Monthly Calendar Widget does not update currentdate

### ISSUE THREAD

**Issue by le-mikcho** [SimpleMobileTools/Simple-Calendar#1711] opened 2022-05-09 12:19 UTC
The current date does not update in the monthly widget 
![IMG_20220509_140143](https://user-images.githubusercontent.com/30931686/167407110-b939b559-04e2-4d7a-afaf-101ab1428c0e.jpg)

Today is the 9th but the calender is stuck on the 2nd.

Android version: 12
Stock Rom version: miui 13 
SimpleCalendar version: 6.18.1 pro
Davx5 version: 4.2.0.3

Miui Battery restriction for simple calendar is disabled, meaning no restriction for app activity

**Comment by tibbi** [comment] 2022-05-09 12:52
Does it update if you open the app by clicking the widget or the app icon? Do the top arrows work?

**Comment by tibbi** [comment] 2022-05-09 14:48
right, this is a more generic issue with widget being frozen then. It happens for a long time now and Im aware of it, just found no way around it yet. Not sure if it is the system killing it or whatever. Duplicate of #1231

**Closed by tibbi** 2022-05-09 14:48 UTC
