### ISSUE TITLE
Exceptional overlapping display of events in weekly attempts

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [SimpleMobileTools/Simple-Calendar#1599] opened 2021-12-29 06:51 UTC
When adding several events with the following times, they are not ordered sequentially but overlapped.
startEvent1: 2021-12-30 01:00 
endEvent1: 2021-12-30 01:05

startEvent1: 2021-12-30 01:05
endEvent1: 2021-12-30 01:08

![image](https://user-images.githubusercontent.com/21290038/147634951-fcc0a2d5-ba2f-4ed8-98ca-eaf1dbc24468.png)

**Comment by ZhuSniffsTheRose** [comment] 2021-12-29 06:51
version： 
![image](https://user-images.githubusercontent.com/21290038/147635101-bb36f102-0d88-425c-b675-2630f8e5bea6.png)

**Comment by tibbi** [comment] 2021-12-29 07:53
duplicate of #1588

**Closed by tibbi** 2021-12-29 07:53 UTC

**Comment by ZhuSniffsTheRose** [comment] 2021-12-29 07:54
it's not same......
