### ISSUE TITLE
memory-using issue

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [SimpleMobileTools/Simple-Calendar#1573] opened 2021-12-08 02:45 UTC
there's a memory-using issue. it could cause oom that events too many to count. when the user adds an event, the app updates all events. Can Simple-calendar support just update the event just added instead update all?

**Comment by tibbi** [comment] 2021-12-08 11:26
duplicate of #1530

**Closed by tibbi** 2021-12-08 11:26 UTC

**Comment by ZhuSniffsTheRose** [comment] 2021-12-09 01:52
Is there a plan to fix it?

**Comment by tibbi** [comment] 2021-12-09 10:44
sure, but it is hard to reproduce and fix

**Comment by ZhuSniffsTheRose** [comment] 2021-12-09 11:15
It's not necessary to reproduce, just supports updating only one event instead of all when adding an event.
