### ISSUE TITLE
Widgets with event or task type selection

### ISSUE THREAD

**Issue by gg-gg1** [SimpleMobileTools/Simple-Calendar#2046] opened 2023-04-10 22:02 UTC
Hi! Would be possible add widgets with the function to choose which type of event to show? For example to add 2 widgets: one with birthdays and one with bank holidays, or tasks.

Thanks!

**Comment by Aga-C** [comment] 2023-04-11 05:15
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1450.

**Closed** 2023-04-11 07:05 UTC
