### ISSUE TITLE
App closes completely instead of switching to standby

### ISSUE THREAD

**Issue by FelixAlt** [SimpleMobileTools/Simple-Calendar#526] opened 2018-06-14 15:26 UTC
When using the home button or switching to the recent apps view, Simple Calendar completely closes and doesn't show up in the recent apps list. This is extremely annoying, as you can't switch to another app to check whether you entered the correct date without resetting the event form.

The phone this is happening on is running Android 7.0, while it works fine on my old one with Android 4.4.

The same thing occurs with seemingly all other simple apps as well.

**Comment by tibbi** [comment] 2018-06-14 19:16
I cannot reproduce it and so far nobody reported it. Dont you have some weird launcher or a rooted device? It must be a device issue.

**Comment by FelixAlt** [comment] 2018-06-14 19:55
This doesn't happen with any other apps as far as I can tell. My phone isn't rooted and I tried switching from Nova Launcher to TouchWiz, but the issue persisted.

**Comment by tibbi** [comment] 2018-06-14 20:15
well guess I can keep it here, we will see.

**Comment by Simon8261** [comment] 2018-06-16 23:20
I am experiencing the same problem as described above using Android 7 on Samsung A3 (2017) App closes and does not persist in memory as soon as screen is switched or minimised and does not persist in task list, making it virtually unusable for my purposes.

**Comment by FelixAlt** [comment] 2018-06-17 05:17
Interesting, I'm using an A3 2016.

**Comment by MannorGH** [comment] 2018-06-29 15:46
I fiddled around a little again and found the cause of the issue. It only happens when using a non default colour for the app icon, with the standard orange everything works fine for whatever reason.

**Comment by FelixAlt** [comment] 2018-06-29 15:48
I think I figured out the cause of this problem. It only happens when I set the app icon colour to a non default one, with the standard orange everything works fine for whatever reason.

**Comment by Simon8261** [comment] 2018-07-01 07:50
Thank you for the above work round to this problem, just seen your posting
and restored the app to default icon colour and it now remains in task list
memory, obviously a bug that hopefully will be resolved in the next update
release.

**Comment by tibbi** [comment] 2018-08-05 20:55
some icon related things have changed, make sure you have the latest version. If it is still broken even after you change the icon, reopen it.

**Closed by tibbi** 2018-08-05 20:55 UTC
Labels: bug
