### ISSUE TITLE
Show events at same time 

### ISSUE THREAD

**Issue by jeanpalaz** [SimpleMobileTools/Simple-Calendar#517] opened 2018-06-05 15:44 UTC
Hello
I have multiple Calendars (and sharing others)
But if 2 events (or more) are at the same time/date, we don't have a clear view, only one is shown, hiding the others.
Is there a way to display or show multiple events, please?

PS: Nice Apps, THX

**Comment by tibbi** [comment] 2018-06-05 15:47
you mean the weekly view? That needs to be improved.

**Comment by tibbi** [comment] 2018-06-06 08:00
ok Im aware of it, it is a duplicate of #194

**Closed by tibbi** 2018-06-06 08:00 UTC
