### ISSUE TITLE
Allow saturday as the first day of the week

### ISSUE THREAD

**Issue by niyumard** [SimpleMobileTools/Simple-Calendar#1534] opened 2021-11-04 14:48 UTC
[In some countries](https://commons.wikimedia.org/wiki/File:First_Day_of_Week_World_Map.svg) like Iran, Saturday is the first day of the week. Currently the app only allows Sunday and Monday to be the first day of the week, please add support for changing the view with Saturday as the first day of the week as well.

**Comment by tibbi** [comment] 2021-11-05 13:55
duplicate of #582

**Closed by tibbi** 2021-11-05 13:55 UTC
