### ISSUE TITLE
ics import issues

### ISSUE THREAD

**Issue by AeliusSaionji** [SimpleMobileTools/Simple-Calendar#461] opened 2018-04-23 18:42 UTC
Hello! I have a few issues with this.

- Opening an ics with simplecalendar doesn't always work. Every other time I try, calendar opens, but the import options do not appear.
- Location field is not imported from ics
- I cannot set my CalDav account as the default import account.

More generally, I think it might be useful to have a function which previews the event, so we can see what is inside the ics before importing. Perhaps that should be the default: always show a detail-view of the ics events. 'Import this event' button would bring us to import screen.

Thanks!

**Comment by tibbi** [comment] 2018-05-02 07:46
I cannot reproduce the location issue. Can you open the .ics file with some text editor and look for a line starting with "LOCATION:" and copypaste me the whole line? Maybe then Ill be able to reproduce it.

**Comment by AeliusSaionji** [comment] 2018-05-03 00:16
```
LOCATION;LANGUAGE=en-US:The center of the universe
X-MICROSOFT-LOCATIONSOURCE:None
X-MICROSOFT-LOCATIONS:[{"DisplayName":"The center of the universe"\,"LocationAnnotation":""\,"LocationUri":""\,"LocationStreet":""\,"LocationCity":""\,"LocationState":""\,"LocationCountry":""\,"LocationPostalCode":""\,"Loca
 tionFullAddress":""}]
```

**Comment by tibbi** [comment] 2018-05-04 14:32
It should be fixed in the next version but Im not using Microsoft products, so let me know if there is another field not imported properly. Thanks

**Closed** 2018-05-04 14:32 UTC
Labels: feature request
