### ISSUE TITLE
v2.10.1 and newer fails to build on F-Droid

### ISSUE THREAD

**Issue by breversa** [SimpleMobileTools/Simple-Calendar#283] opened 2017-11-30 15:38 UTC
https://f-droid.org/wiki/page/com.simplemobiletools.calendar#2.10.1

**Comment by tibbi** [comment] 2017-11-30 15:44
they apparently dont have the latest SDKs on their machine yet... They fail quite a bit lately, it is reported at https://forum.f-droid.org/t/is-the-f-droid-build-process-currently-broken/195/32 . Ill leave the ticket here just as reminder to check f-droid from time to time, but there's nothing I can do on my side.

**Comment by breversa** [comment] 2017-11-30 16:00
Thank you for your lightning-fast reply. :-)
I'm glad to know that this issue is on the F-Droid side. I thought of it but I wasn't sure.

**Comment by tibbi** [comment] 2017-12-05 14:44
so ill close this as a duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/42

**Closed by tibbi** 2017-12-05 14:44 UTC
Labels: bug

**Comment by breversa** [comment] 2017-12-06 09:39
2.12.0 builds fine again on F-Droid : https://f-droid.org/wiki/page/com.simplemobiletools.calendar#2.12.0 :-)

**Comment by tibbi** [comment] 2017-12-06 11:16
thats a good sign, Ill see if the 3.0 versions build too
