### ISSUE TITLE
No calendar app association

### ISSUE THREAD

**Issue by dardoor** [SimpleMobileTools/Simple-Calendar#229] opened 2017-09-28 13:43 UTC
It seems that Simple Calendar doesn't get registered as a calendar app. I tried opening it from another app (a widget) and I got the message "Calendar app not found".

**Comment by tibbi** [comment] 2017-09-28 13:49
this is the oldest issue reported by me, I will have to take a look at it one day already :) For now im closing it as its the duplicate of #9

**Closed by tibbi** 2017-09-28 13:49 UTC
