### ISSUE TITLE
Add a tick button on Task/Event to quick mark it as complete 

### ISSUE THREAD

**Issue by chromer030** [SimpleMobileTools/Simple-Calendar#2240] opened 2023-10-26 16:54 UTC
Currently we should navigate to task/event and scroll to end to mark it.
Please add a tick.

**Comment by Aga-C** [comment] 2023-10-26 17:10
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1804.

**Closed** 2023-10-26 20:49 UTC
