### ISSUE TITLE
Feature Request: Show recurrence number/ age on recurring events

### ISSUE THREAD

**Issue by jayjay991** [SimpleMobileTools/Simple-Calendar#1183] opened 2020-08-05 09:55 UTC
Hi,

First of all I want to thank you for such an amazing suite of apps. It is very much appreciated.

As suggested in the title is there an option to show the recurrence number of a recurring item? I use Rainlendar on my desktop and it has this feature where, for example on birthdays (only if the category is set to birthdays) it shows the age of the person (which is essentially how many times the item has recurred). See image below

Thanks,

![Capture](https://user-images.githubusercontent.com/34886607/89399068-db2c1c00-d709-11ea-9990-0df9bc8ddf7f.PNG)

**Comment by tibbi** [comment] 2020-08-05 21:25
duplicate of #61

**Closed by tibbi** 2020-08-05 21:25 UTC
