### ISSUE TITLE
Automatic backup ICS

### ISSUE THREAD

**Issue by IvanBerestnev** [SimpleMobileTools/Simple-Calendar#1678] opened 2022-03-23 21:48 UTC
Hello! I use a simple calendar.
I need to backup my calendar automatically. Preferably without the use of third-party applications. Now this is only possible manually. Please tell me how to do it. I have LineageOS installed, rooted and termux installed. Thx!

**Comment by tibbi** [comment] 2022-03-23 22:47
nope, you cannot do it yet. Duplicate of #174

**Closed by tibbi** 2022-03-23 22:47 UTC
