### ISSUE TITLE
Feature request: work on ics file directly

### ISSUE THREAD

**Issue by dessalines** [SimpleMobileTools/Simple-Calendar#689] opened 2018-11-06 20:44 UTC
I'm using syncthing to keep my calendar on my desktop and mobile in sync, but this requires me to export and import every single time a change is made. Is there any way to have simple calendar work on the file directly? IE autosave and autoimport any ics file changes made. 

Gnome calendar already does this.

**Comment by tibbi** [comment] 2018-11-06 20:49
there is currently no way you can do it, also I dont think it will be added anytime soon. Duplicate of #169

**Closed by tibbi** 2018-11-06 20:49 UTC
