### ISSUE TITLE
Feature request: Mark events as done

### ISSUE THREAD

**Issue by santiago-espinosa** [SimpleMobileTools/Simple-Calendar#1091] opened 2020-03-08 06:08 UTC
As a student, I often use this app to keep track of different assignments, exams, or chores that I have to do before a certain time. But, this means that a lot of my reminders for work that is already done still pop up in the same color as those that are not.

It would be nice to be able to mark an even/reminder as done in have it show in the same way that previous events look:

![app_3](https://user-images.githubusercontent.com/40335919/76157638-3bf8fd80-6146-11ea-8573-d43b4cd28e16.jpg)

so that the app can also be used for setting reminders, and not only events.

I guess further down the line, you could also add an option to suppress the notifications for events marked as 'done', but that might mean too big of a change to the app so that might be a long-term goal.

**Comment by tibbi** [comment] 2020-03-08 08:22
events cannot be done, those are tasks. So it is a duplicate of #60

**Closed by tibbi** 2020-03-08 08:22 UTC
