### ISSUE TITLE
No notification(s) for subsequent occurence of recurring task

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Calendar#1832] opened 2022-09-07 17:34 UTC
When a task is marked as "to be repeated", the (set) notification is triggered only for the first occurrence.

### Steps to reproduce

1. Create task (not event) with notification repeated for 3 days.

### Expected behavior

There are 3 system notifications triggered.

### Current behavior

There is just one notifcation triggered for the first (original) task occurrence.

### Additional info

The problem doesn't occur for (recurring) events.

6.19.0 Pro, Android 12.

**Comment by tibbi** [comment] 2022-09-10 21:36
duplicate of #628

**Closed by tibbi** 2022-09-10 21:36 UTC

**Comment by szpak** [comment] 2022-09-10 21:46
Hmm, the same seems to work for a regular event (not a task). I will verify it with just 3 reminders (as mentioned in #628).

**Comment by szpak** [comment] 2022-09-12 18:38
Today I added a task and an event. 7 repetitions, the same time and notification settings. On the second occurrence, I have a notification for an event, but not for a task (for the first one, I had them both). I tried it 3 times and the effect is the same - only for tasks. Are you sure there is no difference in notifications for tasks and events?

**Comment by szpak** [comment] 2022-09-21 20:47
You might be right. When I restart my phone in the evening, a notification for the recurring task is shown in the morning :-/.

Maybe it is related to #1805 and effectively to #1644.

As a bonus, I have found #1844 :-).
