### ISSUE TITLE
Feature request: Location/place in event entry

### ISSUE THREAD

**Issue by varakh** [SimpleMobileTools/Simple-Calendar#216] opened 2017-09-09 22:31 UTC
Adding a place/location input field for the event (local and caldav) would be nice. A first version could only allow free text without any geo data. CalDAV also supports this.

**Comment by tibbi** [comment] 2017-09-10 07:57
you can use the "Description" field for it, I dont want to add another free text field. Maybe in the far future when proper coordinates will be selected through a map.

**Comment by tibbi** [comment] 2017-09-15 20:45
it shouldnt really be difficult to implement, I just have to check some calendars about the general user experience. If its mostly free text, or there is some way of selecting coordinates etc.

**Comment by jojbak** [comment] 2017-09-15 20:45
I also think this feature is important, my schedule for school uses the "Location" field to specify the rooms for lectures etc., without this feature the app is unfortunately a no-go for me and probably many other users who use the app for similar things. I could look into adding this feature but I am interested of knowing whether this is going to be merged, as varakh above mentioned.

**Comment by AeliusSaionji** [comment] 2018-01-07 05:47
Could we tweak the way this works a little?

For me, expected behavior when tapping an address is to open the Maps app.

In Simple Calendar, tapping the address just lets me edit the text.

**Comment by tibbi** [comment] 2018-01-07 08:32
google calendar doesnt open the maps either, but I might tweak it somehow in the future.

**Comment by AeliusSaionji** [comment] 2018-01-07 09:11
My google calendar does actually open Maps- maybe it's because I'm on Oreo?

**Comment by tibbi** [comment] 2018-01-07 09:14
not sure, my doesnt on Android 7. Anyway I will just add a map icon at the right side of the Location field, in case someone wants to open a map.

**Comment by tibbi** [comment] 2018-01-09 21:01
what is the expected behaviour here? Google Maps should return a user-readable address, or GPS coordinates? Does some app try to navigate you to the event?

**Comment by AeliusSaionji** [comment] 2018-01-09 21:18
Maps doesn't return anything: I only expect to send the `Location` field to the maps app. It is up to the user to create calendar entries with complete addresses that Google Maps can understand.

Not specifically Google Maps of course, just the maps app registered as default with the system.

**Comment by AeliusSaionji** [comment] 2018-01-09 21:30
Google Maps is pretty intelligent about this.

I just created a test event in Simple Calendar with the location `Daytona International Airport`. Nothing more. Navigate to this event in Google Calendar and tap on the location- this causes Google Maps to open with `Daytona International Airport` in the search bar and the airport is displayed on the map. All I have to do is tap "Directions".

Flow:
Open calendar > tap location > [maps is automatically opened] > tap "Directions" > [GPS navigation has begun].

**Comment by tibbi** [comment] 2018-01-09 21:36
ok thanks, I will check what are my options. I already added a map button to the end of the location field. After pressing it maps will open with the currently filled Location as a parameter, not sure what can the maps return yet. For sure I want to fill in something in the Location field after successfully returning from them, ideally a user-readable address, some place name, or whatever will I receive.

**Comment by AeliusSaionji** [comment] 2018-01-09 22:17
Do you mean to say you're looking to use map data to assist in filling out the location field?

That would be neat, as long as I'm still able to quickly set the location as the destination in maps for use with driving.

**Comment by tibbi** [comment] 2018-01-09 22:20
ye ideally Id like to receive the address from the map and fill it in, Im going to play around with it to see what can I do

**Comment by tibbi** [comment] 2018-01-09 22:45
meh, doesnt look like I can receive anything from maps at all. I would have to add the PlacePicker Google API and a couple new permissions which would freak out quite a lot of people. Guess I will just add a navigation button then.

**Comment by tibbi** [comment] 2018-01-09 23:24
ok so I wont automatically launch the navigation, just display the inserted freetext location on a map. I might detect and parse geodata better in the future, but it wont get much smarter than that

**Comment by AeliusSaionji** [comment] 2018-01-10 00:48
I think it's the responsibility of Maps to understand what you give it, that isn't Calendar's job :)

**Closed** 2018-01-19 15:36 UTC
Labels: feature request

**Comment by tibbi** [comment] 2018-01-19 15:37
ok I added lat/lon parsing attempt from location field, I dont think it will get any better so Ill close it. Let me know if some lat/lon format isnt parsed properly, for now they can be separated by either a comma or a colon.
