### ISSUE TITLE
When the calendar is synchronized to an account, the option to give event type and color to the event is eliminated? How can I add it?

### ISSUE THREAD

**Issue by cetrun** [SimpleMobileTools/Simple-Calendar#667] opened 2018-10-21 18:36 UTC
When the calendar is synchronized to an account, the option to give event type and color to the event is eliminated? How can I add it?

**Comment by tibbi** [comment] 2018-10-21 18:38
ye currently you cannot do it, but improving it is on the roadmap. This is basically a duplicate of #653

**Closed by tibbi** 2018-10-21 18:38 UTC
