### ISSUE TITLE
An error occurred: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by schalami** [SimpleMobileTools/Simple-Calendar#1160] opened 2020-06-16 13:59 UTC
Hi,

i don't really have a problem, at least I don't notice it in the everyday use. But I keep getting a error message on the home screen and i don't know where this is coming from.

`An error occurred: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a111, calling Package: com.simplemobiletools.calender.pro`

Is this a problem from Simple Calendar or DAVx5? Any tips what i can do to figure this out?

Thanks Marcel

**Comment by tibbi** [comment] 2020-06-16 14:01
duplicate of #1037 , you can find more info there

**Closed by tibbi** 2020-06-16 14:01 UTC
