### ISSUE TITLE
No color choice on Dav sync calendar

### ISSUE THREAD

**Issue by AqwelF** [SimpleMobileTools/Simple-Calendar#495] opened 2018-05-18 13:36 UTC
When i want to change the color of a dav sync calendar i have a blank rectangle !

![Screenshot](https://i.imgur.com/VVO0xVM.jpg)

The option works on local calendar.

Thus issue appear after the last update

Mobile : Huawei Honor 9
Android : 8.0 oreo stock rom under EMUI 8
Version app : 4.0.3

Thanks.

**Comment by tibbi** [comment] 2018-05-18 15:26
are you sure this specific calendar worked in previous versions? wasnt it crashing when you clicked on the color?

**Comment by AqwelF** [comment] 2018-05-18 17:32
Do you think at least making the color icon app panel as large as the in app font color ? There so much good and deep color in the in app color panel. Really beautifull.-------- Message original --------Objet : Re: [SimpleMobileTools/Simple-Calendar] No color choice on Dav sync calendar (#495)De : Tibor Kaputa À : SimpleMobileTools/Simple-Calendar Cc : AqwelF ,Author are you sure this specific calendar worked in previous versions? wasnt it crashing when you clicked on the color?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SimpleMobileTools/Simple-Calendar","title":"SimpleMobileTools/Simple-Calendar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SimpleMobileTools/Simple-Calendar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tibbi in #495: are you sure this specific calendar worked in previous versions? wasnt it crashing when you clicked on the color?"}],"action":{"name":"View Issue","url":"https://github.com/SimpleMobileTools/Simple-Calendar/issues/495#issuecomment-390243222"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [SimpleMobileTools/Simple-Calendar] No color choice on Dav sync calendar (#495)","sections":[{"text":"","activityTitle":"**Tibor Kaputa**","activityImage":"https://avatars3.githubusercontent.com/u/528931?s=160\u0026v=4","activitySubtitle":"@tibbi","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"SimpleMobileTools/Simple-Calendar\",\"issueId\":495,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"SimpleMobileTools/Simple-Calendar\",\"issueId\":495}"},{"targets":[{"os":"default","uri":"https://github.com/SimpleMobileTools/Simple-Calendar/issues/495#issuecomment-390243222"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":336789148}"}],"themeColor":"26292E"}

**Comment by tibbi** [comment] 2018-05-18 20:37
you couldnt, caldav doesnt really support colors, just in some rare cases. Anyway it is a duplicate of #361 so Ill close it, dont really expect it changing anytime soon though

**Closed by tibbi** 2018-05-18 20:37 UTC
