### ISSUE TITLE
Feature Request: Add a week view widget.

### ISSUE THREAD

**Issue by Magnesium117** [SimpleMobileTools/Simple-Calendar#2204] opened 2023-09-19 20:07 UTC
I really enjoy using your calender. However I think a week view widget would improve it. I find that the week view is the best way to see upcomming events and especially see when to be where. Thats why I would really like to have it on my home screen.

**Comment by Aga-C** [comment] 2023-09-19 20:12
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/398.

**Closed** 2023-09-19 20:14 UTC
