### ISSUE TITLE
Issue with deleting entries

### ISSUE THREAD

**Issue by Domino2017** [SimpleMobileTools/Simple-Calendar#521] opened 2018-06-08 14:30 UTC
I don't know if this is a bug or if I'm doing something wrong, but. I have monthly entries set up. When I tried to delete all the entries after the 'current' one, Simple Calendar deletes all the entries, even past ones. Is there a way for me to keep past entries intact and only delete future ones?

**Comment by tibbi** [comment] 2018-06-08 16:01
well you should see a dialog at deleting repeating events where you can select which events you want to delete. For now there isnt even an option for deleting only the future events, it will be added in the future. Duplicate of #243

**Closed by tibbi** 2018-06-08 16:01 UTC

**Comment by Domino2017** [comment] 2018-06-08 17:11
Was afraid of that, thanks though Tibbi.
