### ISSUE TITLE
Week View Freezes on App re-open

### ISSUE THREAD

**Issue by Mmedic23** [SimpleMobileTools/Simple-Calendar#359] opened 2018-02-12 15:53 UTC
When I close and reopen the app while it's on week view, the week view freezes completely. Doesn't happen everytime, more like 1 in 10 reopens or so. It appears only the week view is frozen though, switching to other views works, but returning to weekly view doesn't fix it. All other functions of the app aren't affected.

**Comment by Mmedic23** [comment] 2018-02-12 19:16
Also forgot to mention clearing app from Recents doesn't fix, but force stop does fix. Android 7.1.2 (LineageOS 14.1 20180101-nightly-athene)

**Comment by tibbi** [comment] 2018-02-12 19:20
Like how many events do you have created for that week + - 1 week? Is it some huge amount? What app version and Android OS version do you have?

**Comment by tibbi** [comment] 2018-02-13 20:05
ok, weird. Do you have CalDAV sync enabled in settings?

**Comment by Mmedic23** [comment] 2018-02-13 20:07
Nope.

**Comment by Mmedic23** [comment] 2018-02-17 20:33
It hasn't been happening since I opened this, and it happened again. Some additions:

I hadn't opened the app at all for a few days before the freeze.

The app is always in week view, so that means I close it and open it while it's in week view all the time.

Left/right swipes changed the "Week n" text properly, settings menu where you add holidays and stuff opens properly, it's just the main calendar screen that's frozen in place.

Could it be device specific somehow? This seems hard to reproduce and it doesn't look like many people are sharing this issue.

**Comment by Mmedic23** [comment] 2018-02-17 20:34
Actually nevermind that last paragraph, my issue is exactly the same as #264.

**Comment by Mmedic23** [comment] 2018-02-17 20:36
Not "exactly" the same, the only difference being my events + time axis don't move.  God I'm sorry I'm commenting so fast without thinking.

**Comment by tibbi** [comment] 2018-02-17 21:32
Most people report blank views, not this one. Ill check what could go wrong there.

**Comment by bramboomen** [comment] 2018-02-20 10:55
I can confirm this bug. After I havent opened the app in a while, upon opening the week view is stuck. All the other elements are working exept the main view. For example, if I open the event list view from the menu, it will be drawn on top of the stuck week view, but otherwise work fine. For me, hitting back and reopening the app fixes the issue. The fact that it happens after a period of inactivity makes me think it has something to do with android's doze option, so I will make an exeption in the battery settings and see if that changes anything.

I am on version 3.3.0, android 7.0 LG G6 (H870DS stock)

**Comment by bramboomen** [comment] 2018-02-20 23:16
As it turns out, turning off battery optimalization did not fix the issue.

**Comment by tibbi** [comment] 2018-02-21 13:51
do you usually exit the app properly with the Back button, or just pause it with the Home button?

**Comment by bramboomen** [comment] 2018-02-21 13:59
I suppose I usually pause it. But I can't be sure if it happens when exiting via the back button.

**Comment by tpo** [comment] 2018-03-06 07:55
After upgrading to 3.2.2 it's got a bit better:

- when I don't use SimpleCalendar for a while (and switch between apps), then as before, the weekly view doesn't render the appointments
- however at least, when I terminate the app, then on reopening SimpleCalendar, the appointments are there again

**Comment by tibbi** [comment] 2018-06-12 20:27
check with 4.1.0, some things have been improved

**Comment by tibbi** [comment] 2018-06-12 20:28
check with 4.1.0, some things have been improved

**Comment by bramboomen** [comment] 2018-06-19 06:22
For me on 4.1.0, the issue still persists.

**Comment by tibbi** [comment] 2018-12-19 18:37
so recheck with 6.1.1 please, some things have changed again

**Comment by tibbi** [comment] 2018-12-25 22:36
ok I found the issue, it should be really fixed in 6.1.2 already

**Closed by tibbi** 2018-12-25 22:36 UTC
Labels: bug

**Comment by tpo** [comment] 2018-12-29 12:36
tibbi wrote:

> so recheck with 6.1.1 please, some things have changed again

I would like to, however here's my problem:

- I run lineage without all the Google stuff
- the reason I don't have all the Google stuff installed is because I *despise* the "Big Brother" part of Google's character. I just don't want any of it's tracking, profiling, closed source artificial intelligence gaining more and more power near me.
- not having all the Google stuff installed doesn't let me to use Google Play to pay for the new Simple* tools, even think it's a good thing to contribute finanancially
- there are ways to get the APK via another mobile device and have it installed on my Lineage phone, however it's all very complicated and time intensive so I won't be doing that as a general rule
- also some packages are checking online with Google - as far as I understand - whether the user has "licensed" them with, a features that my lineage phone won't ever be able to provide as far as I understand unless I fully surrender to the Borg aka Google, which I won't
- since as I understand it you are no longer developing the free versions of the Simple tools but only the paid ones, it seems line I won't be able to test those :-( I am very sorry to say (unless I find some way to interact with the Borg without sinking a lot of time into the task and without surrendering all of my data completely to them)

**Comment by tibbi** [comment] 2018-12-29 16:14
the pro versions are available on f-droid for free too, as new apps. For example the Calendar is at https://f-droid.org/packages/com.simplemobiletools.calendar.pro

**Comment by tpo** [comment] 2018-12-29 17:33
> the pro versions are available on f-droid for free too, as new apps. For example the Calendar is at https://f-droid.org/packages/com.simplemobiletools.calendar.pro

Woah, **way cool**, thanks!

One question - the "old" (non-pro) version and the pro version in F-Droid have - as far as I can tell - the same name, the same icon, the same everything (apart from the version). So there's no way to distinguish them there (AFAICS). This is a minor problem as far as I can see - should I open an issue for that?

**Comment by tibbi** [comment] 2018-12-29 21:58
F-droid was supposed to redirect users from old version to the new one or at least write some note there, but they are generally quite slow. I hope one day it will get sorted out. Anyway, the Pro versions should have the "Pro" appended to the title and the url has .pro appended too. It might not be visible in the f-droid app though.

**Comment by bramboomen** [comment] 2018-12-29 22:01
I haven't tested extensively, but the app seems to restart properly when I open it after a while, which means that I have not encountered this issue once in the last days. So it seems this issue is indeed fixed. Thank you for your effort!
