### ISSUE TITLE
custom date format for better regional adaptability

### ISSUE THREAD

**Issue by Glasses8448** [SimpleMobileTools/Simple-Calendar#1405] opened 2021-06-24 17:25 UTC
The date format in simple-calendar is: 
June 24 2021 (Do.)
The common date format in my region (germany) is:
Do. 24.06.2021

It is quite unplesent to juggle these numbers and words in my head, while arranging an appointment by telephone. I wish that I could change the date format according to my personal prefences, like I'm used to in xfce-desktop-enviroment. 
![xfce](https://user-images.githubusercontent.com/53970121/123306470-9f689380-d521-11eb-804f-012c374a4e5b.png)
![2021-06-24 19 00 07](https://user-images.githubusercontent.com/53970121/123306471-a099c080-d521-11eb-90dc-f9b9bdbb8c81.png)
![2021-06-24 18 59 12](https://user-images.githubusercontent.com/53970121/123306474-a2638400-d521-11eb-9d76-5904d2f5daef.png)

**Comment by tibbi** [comment] 2021-06-24 20:02
duplicate of #1055

**Closed by tibbi** 2021-06-24 20:02 UTC
