### ISSUE TITLE
Not possible to handle different time zone

### ISSUE THREAD

**Issue by letypequividelespoubelles** [SimpleMobileTools/Simple-Calendar#971] opened 2019-09-01 20:28 UTC
It would be very nice that the calendar handle different time zone. Even while synchronising framagenda calendar (which enable different time zone), simple calendar does wrong thing.

**Comment by tibbi** [comment] 2019-09-02 06:47
duplicate of #436

**Closed by tibbi** 2019-09-02 06:47 UTC
