### ISSUE TITLE
Feature Request: add tasks just like google calendar

### ISSUE THREAD

**Issue by popev** [SimpleMobileTools/Simple-Calendar#1401] opened 2021-06-22 08:06 UTC
Please add a option to add tasks supporting caldav protocol.
![Snipaste_2021-06-22_16-04-10](https://user-images.githubusercontent.com/73465450/122887681-b5d0ec80-d373-11eb-9b15-187abe163925.png)

**Comment by tibbi** [comment] 2021-06-22 09:38
duplicate of #60

**Closed by tibbi** 2021-06-22 09:38 UTC
