### ISSUE TITLE
add support for dark theme

### ISSUE THREAD

**Issue by 532910** [SimpleMobileTools/Simple-Calendar#874] opened 2019-05-04 01:58 UTC
1. menu ignores colors customization
2. menu opened by hardware menu button is bad visible as gray on white 

![image](https://user-images.githubusercontent.com/14617699/57172438-b7a06480-6e28-11e9-9da7-7357ee6cb720.png)

![image](https://user-images.githubusercontent.com/14617699/57172445-c129cc80-6e28-11e9-82e3-b9dc4c60e46f.png)

**Comment by tibbi** [comment] 2019-05-04 07:33
improving it is on the roadmap, it affects all apps. Duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/108

**Closed by tibbi** 2019-05-04 07:33 UTC
