### ISSUE TITLE
Not detected as calendar app?

### ISSUE THREAD

**Issue by LazyT** [SimpleMobileTools/Simple-Calendar#1859] opened 2022-10-19 09:59 UTC
Simple Calendar does not appear in the list of installed calendar apps.

Others, such as Etar or aCalendar are displayed and can be selected as default.

Is this a problem from the selecting app or Simple Calendar?

**Comment by tibbi** [comment] 2022-10-19 10:31
where do you mean? What app version are you using?

**Comment by LazyT** [comment] 2022-10-19 10:52
Tested with https://codeberg.org/BeoCode/Weather.

In the widget you can click on the date and it opens the calendar app. But SC isn't listed there.

**Comment by tibbi** [comment] 2022-10-19 11:43
guess they are using an intent that we dont support yet, it isnt an issue with recognizing as a calendar in general

**Comment by LazyT** [comment] 2022-10-19 12:35
Ok, thanks for the info.

**Comment by falzonv** [comment] 2022-11-05 10:48
Hello @tibbi,

I also had this issue reported by a Discreet Launcher user (https://github.com/falzonv/discreet-launcher/issues/238#issuecomment-1297430588).

Since @LazyT said that Etar was properly detected, I checked its Manifest and saw that it has the category "APP_CALENDAR" which doesn't seem to be declared in Simple Calendar:
https://github.com/Etar-Group/Etar-Calendar/blob/master/app/src/main/AndroidManifest.xml#L77

Both Discreet Launcher and the widget mentioned by @LazyT are using this category to recognize calendar apps so this is probably the reason why Simple Calendar is not detected:
https://codeberg.org/BeoCode/Weather/src/branch/main/app/src/main/java/de/beowulf/wetter/widget/TimeWidget.kt#L53
https://github.com/falzonv/discreet-launcher/blob/main/app/src/main/java/com/vincent_falzon/discreetlauncher/ViewClock.java#L335

Could you try to add the category "APP_CALENDAR" in the Simple Calendar Manifest?
It seems that this should be enough to solve this issue.

Best regards.

**Comment by tibbi** [comment] 2022-11-18 19:02
couldnt reproduce the issue with the weather app, will see if it gets fixed in 6.20.2. Thanks

**Closed** 2022-11-18 19:01 UTC
Labels: feature request

**Comment by LazyT** [comment] 2022-11-21 13:31
New version makes no difference here.

**Comment by tibbi** [comment] 2022-11-21 13:36
would be good to find a real case scenario with that bug though, the Weather app you linked isnt really used by anyone

**Comment by falzonv** [comment] 2022-12-03 15:27
Hello @tibbi,

I tested as well with Discreet Launcher and I confirm it didn't work :-/

Here are more details about my tests:
- Test environment:
  - Smartphone using LineageOS 18.1 (based on Android 11)
  - 3 calendar apps for testing:
    - LineageOS version of Etar (`org.lineage.etar`, pre-installed but can be disabled)
    - F-Droid version of Etar (`ws.xsoh.etar`, v1.0.30, installed for testing as the LineageOS one is a system app)
    - Simple Calendar (`com.simplemobiletools.calendar.pro`, v6.20.3, installed from F-Droid)
  - Discreet Launcher v6.6.1, where the call trying to open the default calendar looks like:
    - `startActivity(Intent.makeMainSelectorActivity(Intent.ACTION_MAIN, Intent.CATEGORY_APP_CALENDAR)) ;`
- Discreet Launcher configuration:
  - "Appearance > Clock format" : one of the two formats showing the date is selected
  - "Operation > Interactive clock" is enabled (so that when the user clicks the date, the call above is triggered to try to open the default calendar app)
- Test results (after a click on the date):
  - If there is only the LineageOS Etar (the 2 other apps uninstalled), it opens directly.
  - If there is only the LineageOS Etar and Simple Calendar, the LineageOS Etar opens directly.
  - If there is only the F-Droid Etar and Simple Calendar (LineageOS Etar disabled), the F-Droid Etar opens directly.
  - If the 3 apps are there, Android displays a menu to choose the default calendar but only the 2 Etars (both LineageOS and F-Droid) are listed, Simple Calendar doesn't appear.
  - If only Simple Calendar is installed, no calendar app is found and Discreet Launcher displays an error message.

I don't know if there are other major open source calendar apps aside Simple Calendar and Etar, that would be interesting to test.

Best regards.
