### ISSUE TITLE
Unexpected reminders for the past/future events 

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Calendar#1805] opened 2022-08-11 20:44 UTC
Recently (for a month?), occasionally, the system reminders (displayed in the top panel) are generated also for the events that were already moved to the future (e.g. to the next week). A few times, I saw an exception displayed in a "tooltip" at the bottom of the screen which (most likely) contained "Concurrent" and "limit" and maybe "exceeded" (unfortunately, it has hidden before I took a screenshot - is it possible to show the application logs somehow?) what could suggest that due to large number of event (1K+, 2K+? Is it possible to count it in the application) there is some problem with the background processing and some of them are not "rescheduled" on time. I realize, it might be hard to reproduce, but maybe you have an idea what happens here?

Tested with 6.19.0 Pro (but the problem occurred also with some earlier version) on Pixel 3a (Android 12).

**Comment by szpak** [comment] 2022-08-16 17:24
I was able to get a screenshot. The error is:
> Error: java.lang.IllegalStateException:
> Maximum limit of concurrent alarms 5...

**Comment by tibbi** [comment] 2022-08-16 19:58
duplicate of #1644

**Closed by tibbi** 2022-08-16 19:58 UTC
Labels: bug
