### ISSUE TITLE
Feature request: Memo event type

### ISSUE THREAD

**Issue by b9AcE** [SimpleMobileTools/Simple-Calendar#1253] opened 2020-12-18 09:48 UTC
It would be useful if there was apart from the regular scheduling type of event also a builtin event type for writing notes/memos like "on this day [possibly also "at this time"] this task was performed", so that users can make notes of e.g. when an application was submitted, some administrative task completed, etc,
whereas now the only apparent way of doing this is to create a faux "scheduled" event in the past with 0 minutes duration at the time in question.

**Comment by tibbi** [comment] 2020-12-18 10:54
Tasks are already reported as one of the oldest thing, still cannot promise any date. Duplicate of #60

**Closed by tibbi** 2020-12-18 10:54 UTC
