### ISSUE TITLE
Bug: all languages default to US date formats (Month DD, YYYY) rather than respecting the language/localisation settings

### ISSUE THREAD

**Issue by emes81** [SimpleMobileTools/Simple-Calendar#2098] opened 2023-06-01 08:09 UTC
If I set Simple Calendar to, say, British English or German, I should see "3 May" or "3 Mai"; Instead, I see "May 3" and "Mai 3," neither of which resemble dates in UK/DE conventions. This creates potential confusion; "Mai 12" would, for instance, can (and is likely) to be understood in German as "the month of May, in the year of 2012".

This should be regarded as a central usability issue in a calendar app.

Hence, when selecting a particular language, that country's date format should be used:

USA: May 3, 2023
UK: 3 May 2023
DE: 3. Mai 2023

and so on

**Comment by Aga-C** [comment] 2023-06-01 08:47
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1055.

**Closed** 2023-06-05 08:22 UTC
