### ISSUE TITLE
feature request: privat tag

### ISSUE THREAD

**Issue by pollloo** [SimpleMobileTools/Simple-Calendar#1835] opened 2022-09-10 18:07 UTC
I wish I could mark an appointment as private. This so that I can invite myself to it in the office and the content of the appointment is not immediately visible to everyone.

This is my first entry on GitHub. So I appreciate any hints if I did not capture this correctly.

**Comment by tibbi** [comment] 2022-09-10 21:35
You should check if the issue isnt reported yet, this one is a duplicate of #1022

**Closed by tibbi** 2022-09-10 21:35 UTC
