### ISSUE TITLE
automatic ics export

### ISSUE THREAD

**Issue by microo8** [SimpleMobileTools/Simple-Calendar#1280] opened 2021-02-10 07:57 UTC
I want to have a ics file for all my events, that I can edit on my phone and my pc and it will be synchronized with syncthing.
Is it possible to add a 'automatic ics export' feature, that will always update a specified ics file?

**Comment by tibbi** [comment] 2021-02-10 09:16
duplicate of #1209

**Closed by tibbi** 2021-02-10 09:16 UTC
