### ISSUE TITLE
[Feature Request] Emable Task Notifications

### ISSUE THREAD

**Issue by Jah-On** [SimpleMobileTools/Simple-Calendar#1685] opened 2022-04-03 23:44 UTC
Hi,

Nice work with the app! Please add an option to send notifications for tasks too. 

Thank you!

**Comment by Aga-C** [comment] 2022-04-04 06:57
It's already requested here: https://github.com/SimpleMobileTools/Simple-Calendar/issues/1660.

**Comment by tibbi** [comment] 2022-04-04 07:18
duplicate of #1600

**Closed by tibbi** 2022-04-04 07:18 UTC
