### ISSUE TITLE
Option to "Hide declined/not going events"

### ISSUE THREAD

**Issue by maxelkins** [SimpleMobileTools/Simple-Calendar#2264] opened 2023-11-14 13:20 UTC
It would be really great if there was an option to hide declined/not going events in the settings and/or in the filters.

Without this it makes reading the cal very difficult, especially when declined events overlap events you are going to.

Appologies if this feature exists, I can't seem to find it. I also checked to see if anyone else has raised this issue, can't seem to find that either so thought I create one.

**Comment by PetitPotiron** [comment] 2023-11-21 13:39
I'm not sure but it looks like a duplicate of issue #2166

**Closed** 2023-11-22 09:16 UTC

**Comment by maxelkins** [comment] 2023-11-22 10:40
I'm not sure I agree that it is the same issue.

We already have a style for declined events (strike-through), its the fact I think we should be able to hide them from the calendar view if they are declined.

Please can you reopen and mark a feature request.

**Comment by maxelkins** [comment] 2023-12-05 17:38
@tibbi please can you reopen this issue :)

**Comment by inson1** [comment] 2023-12-05 18:33
@maxelkins tibbi sold SMT to ad company- SMT are dead, there is already fork - https://github.com/FossifyX
