### ISSUE TITLE
Synchronization issue with 400 error on recurring events

### ISSUE THREAD

**Issue by NicoHood** [SimpleMobileTools/Simple-Calendar#1538] opened 2021-11-10 13:33 UTC
Hi,
I get 400 errors when synching with davx5 and radicale server. I contacted the davx5 support and we debugged it really good:

The issue happens if you
1. Create a weekly repeating event
2. Delete a single entry of that event series
3. sync

It generates the following (sample) entry, which if invalid and therefore rejected by the radicale server:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.0-gplay ical4j/3.1.0
BEGIN:VEVENT
DTSTAMP:20211110T085217Z
UID:2b388553-e36b-44d9-a339-5fb9816aac22
SEQUENCE:1
SUMMARY:Joggen
DTSTART;TZID=Europe/Berlin:20211104T170000
DTEND;TZID=Europe/Berlin:20211104T170000
RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=TH
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT30M
ACTION:DISPLAY
DESCRIPTION:Joggen
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20211110T085217Z
UID:2b388553-e36b-44d9-a339-5fb9816aac22
RECURRENCE-ID;TZID=Europe/Berlin:20211118T170000
SEQUENCE:1
DTSTART;TZID=Europe/Berlin:19700120T004731
DTEND;TZID=Europe/Berlin:19700120T004731
EXDATE:20211117T230000Z
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
LAST-MODIFIED:20201010T011803Z
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19160430T230000
RDATE:19400401T020000
RDATE:19430329T020000
RDATE:19460414T020000
RDATE:19470406T030000
RDATE:19480418T020000
RDATE:19490410T020000
RDATE:19800406T020000
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19471005T030000
RRULE:FREQ=YEARLY;UNTIL=19491002T010000Z;BYMONTH=10;BYDAY=1SU
END:STANDARD
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19800928T030000
RRULE:FREQ=YEARLY;UNTIL=19950924T010000Z;BYMONTH=9;BYDAY=-1SU
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

As you can see the id is duplicated, as well as the VEVENT entry. I tested this with google calendar and it does not happen there.

Here is the response from the davx5 support, it could help you with debugging:

    Thanks for your report. The public bugtracker is our forum; I have now linked it from Github issues of the davx5-ose repo to make it more clear.
    
    I had a look at your report, with the following findings:
    
    You're using Simple Calendar Pro, which inserts the event like this:
    * main_event: data with <RRULE>
    * deleted instance: another data rows of type "exception" (refers to main_event), with DTSTART and EXDATE set to the deleted instance
    
    So DAVx5 generates
    
    BEGIN:VEVENT
    UID:event
    DTSTART:…
    RRULE:…
    END:VEVENT
    BEGIN:VEVENT
    UID:event
    RECURRENCE-ID:<date of exception>
    DTSTART:<date of exception>
    EXDATE:<date of exception>
    END:VEVENT
    
    This is invalid and thus Radicale rejects the iCalendar.
    
    However, as I understand it and as other calendar apps, EXDATE is to be used in the main event. So for an instance, there are two methods:
    
    1.
      * main_event: data with <RRULE> and <EXDATE>(s) for the deleted instances, or
    2. 
      * main_event: data with <RRULE>
      * deleted instance: another data rows of type "exception" (refers to main_event), with DTSTART and STATUS=cancelled
    
    So I think this is a problem of Simple Calendar. Can you please try another calendar app and tell me whether it works?

**Comment by tibbi** [comment] 2021-11-12 09:14
what app and OS version are you using?

**Comment by NicoHood** [comment] 2021-11-12 09:22
Android 10
Simple Calendar (If there is a pro, it is pro) Version 6.15.4

**Comment by NicoHood** [comment] 2021-11-14 16:39
I want to add, that the issue exists quite a long time, but I never really catched why this happens (excluding events). It is quite critical, as the whole calendar stops to sync. Do you have any first idea how to solve this?

**Comment by tibbi** [comment] 2021-11-14 16:44
Im not sure, havent really met many people using Radicale. It seems to work just fine in the popular calendar services.

**Comment by rfc2822** [comment] 2021-11-14 18:46
> Im not sure, havent really met many people using Radicale. It seems to work just fine in the popular calendar services.

It's not a Radicale problem. The problem comes from how exceptions are stored in the Android calendar provider.

**Comment by NicoHood** [comment] 2021-11-14 20:08
If you need a radicale test account, I can give you some via Email. I guess that would be easier for you.

**Comment by NicoHood** [comment] 2021-11-21 12:41
Any updates on that issue? It is really blocking me, as I cannot use recurring events with an excluded event

**Comment by NicoHood** [comment] 2021-12-02 17:46
@tibbi would you please mind having another look at this issue? Sadly it makes the app (mostly) unusable for me. I guess that you as an expert will be able to solve this quite easy, I hope so. If you need I can assist with further testing!

Thanks a lot :)

**Comment by tibbi** [comment] 2021-12-02 20:28
not really, such issues are actually difficult to reproduce and are system/setup specific, so basically edge cases

**Comment by rfc2822** [comment] 2021-12-02 20:32
It should be reproducible with the three easy steps from the first posting and as I understand it, it's neither related to Radicale nor to some server or system-specific property. It's about how Simple Calendar stores exceptions in the Android calendar provider; and this differs from the iCalendar and Android specifications.

**Comment by NicoHood** [comment] 2021-12-03 10:02
Yeah, you can easily validate the ical and see, that there is a duplicated id, that violates the ical spec:
https://icalendar.org/validator.html

![image](https://user-images.githubusercontent.com/6888294/144583972-44eb288e-09a6-4ef4-ba49-1b43ba86e20a.png)

If you need a radicale server to test this on, I can give you access to one. **It is 100% reproducible.**

**Comment by NicoHood** [comment] 2021-12-28 19:57
Any chance? 🥺🥺🥺

**Comment by tibbi** [comment] 2021-12-28 22:13
as mentioned previously, it isnt a priority for now as it is an edge case not happening often. There are more important issues too.

**Comment by jyniybinc** [comment] 2022-03-31 12:33
Any updates on this issue? I also encountered this problem.

**Comment by robjloranger** [comment] 2022-03-31 15:22
This issue is a client issue. I can reproduce when editing a single occurrence of a recurring event.

The problem there is the `RECURRENCE-ID` cannot be the same as the previous entry. The client leaves it as is which results in a 400 error as it must not already exist.

Error returned to the client: `Bad PUT request ... Overwritten recurrence with RRULESET`

For reference: https://www.rfc-editor.org/rfc/rfc5545, section 3.8.4.4.

**Comment by tobse1211** [comment] 2022-08-13 20:59
I have encountered the problem as well, using Simple-Calendar and Radicale.

**Comment by clementefnc** [comment] 2022-08-23 11:43
Problem encountered here as well.

Simple Calendar 6.19.0 PRO
DAVx5 4.2.2-ose

**Comment by NicoHood** [comment] 2022-08-23 13:56
@tibbi Arent enough people affected now? Even more who did not find this github issue would also have this issue. It is a very common usecase.

**Comment by reedts** [comment] 2022-08-24 06:59
imo I don't see how this is a edge case.  For me (and obviously other people as well) this is a very common usecase. I even have a second calendar app (Etar) installed for the sole purpose of removing a single occurrence of a reoccurring event.

I'd very much appreciate if you'd have a look into this @tibbi

**Comment by lmoellendorf** [comment] 2022-11-02 12:08
I am having the same issue. For now I removed Simple-Calendar and installed Etar. However, the error persists. I think I have to delete the bad event. But I don't know how to do so. Can anyone help?

**Comment by kousu** [comment] 2022-11-02 13:44
I was able to delete the bad event with SimpleCalendar.

**Comment by gabriel-berardi** [comment] 2022-12-22 10:49
I had the same issue and switched to Etar for now.

**Comment by tbart** [comment] 2022-12-27 18:54
@tibbi How shall we count the number of people affected? Adding thumbs up to @reedts 's comment above?
Just adding comments for "Me too" does not really improve things.
I'll vote above and say that I'm affected here, as well, for now :)

**Comment by tibbi** [comment] 2022-12-28 09:23
well Im aware of the issue, but if I cannot reproduce it in any way, it is hard to fix

**Comment by NicoHood** [comment] 2022-12-28 09:31
Well you should be able to reproduce this 100% with the steps in the first post. With radicale and davx5 the issue will occur 100%. Maybe with other servers as well, but those are the ones I've tested

**Comment by tbart** [comment] 2022-12-28 13:20
To sum things up
1) This does not really seem to be backend specific.
1b) Even if it is, @NicoHood offered access to a radicale instance, so no setup overhead involved for reproduction.
@NicoHood: Can you probably give @tibbi access details already?
2) There seems to be a specification violation as pointed out by NicoHood above, so that sounds like it should be fixed anyway (and it will most probably fix the resulting issue with (at least) radicale as well). There might be other implementations that are more forgiving, but this should not be relied upon.
3) I'll give my 2c for how I can trigger it in a few seconds:
- Add repeating event (trash collection, every 6 weeks in my case)
- Edit one event of those and shift just this event by one day (very similar to OP's deletion of one event)
- Sync & get "Bad request" (or Patrick West as I call it :) )

I don't want to seem pushy, I am just a sysadmin so I cannot help with Java coding. I am absolutely willing to test or help in other ways I can!

**Comment by rekesz4** [comment] 2023-01-23 18:45
Hi guys,

I recently switched from a nextcloud instance to using mailbox.org and I started getting the same error, so +1 to affected people and probably anyone with a mailbox account. I can provide any further info if needed.

**Comment by tnar-git** [comment] 2023-02-10 05:59
+1

**Comment by kot0dama** [comment] 2023-02-23 08:57
This one bites me everytime I remove an occurrence of a recurring event, and I always forget there's this issue before it's too late... The resolution is quite painful.

Here are some references for this bug on Radicale and Davx5 projects.
https://github.com/bitfireAT/davx5-ose/discussions/66
https://github.com/Kozea/Radicale/issues/1264

Could you please reconsider having a look at this?
I could provide an account on my radicale server for testing purposes.

Thank you

**Comment by filipemosca** [comment] 2023-04-30 16:48
> Hi guys,
> 
> I recently switched from a nextcloud instance to using mailbox.org and I started getting the same error, so +1 to affected people and probably anyone with a mailbox account. I can provide any further info if needed.

I'm having the same problem using Mailbox with DAVx5 and Simple Calendar. Using Etar this error does not occur. So for now I'm using Etar as my calendar app, but I prefer the simple calendar and want to switch back to it after the issue is resolved

**Comment by tibbi** [comment] 2023-05-18 12:42
should be fixed by https://github.com/SimpleMobileTools/Simple-Calendar/pull/2053

**Closed by tibbi** 2023-05-18 12:42 UTC

**Comment by SanskritFritz** [comment] 2024-11-09 09:59
> +1 but to solve the issue all you need to do is to delete the problematic recurring events one by one by one using the 'view item' within the error notification produced by davx5. (And in the future refrain from modifying recurring events too much with simple calendar until the error is fixed..)

I ran into this issue just now using Etar. There is already a [bug report](https://github.com/Etar-Group/Etar-Calendar/issues/1672) for that over at Etar, but the workaround mentioned there worked for me and it was much less painful than deleting events one by one:

> Once in this state, I could only resolve it by unsyncing and resyncing the calendar in DAVx5. I have seen this once before, and resolved it similarly in the past. After syncing back up, making the same edit again did successfully go through.
