### ISSUE TITLE
Add birthdays automatically

### ISSUE THREAD

**Issue by natrius** [SimpleMobileTools/Simple-Calendar#620] opened 2018-09-12 09:09 UTC
Is it possible to add the birthdays automatically? Because i don't want to think everytime i add another contact to press the button again. 
It would be great if this would just be an option in the settings and if ticket the birthdays just gets imported.

**Comment by tibbi** [comment] 2019-01-29 20:36
not sure what you mean with the third point. Accessing contact birthdays needs the Contacts permission, it is asked once the user triggers the "Add contact birthdays" menu item. Then birthdays could be rechecked periodically somehow in the background.

**Comment by jtj9817** [comment] 2019-01-30 06:20
@tibbi Just rethought about the approach to the problem, seems like we can simplify it better. 

- When the "Add Contact Birthdays" option is selected and the user agrees for Contacts access permission, the app will scan current list of Contacts with their Birth Date available
- After adding the current list of Contacts with their Birthdays, SimpleCalendar will prompt user if they want to "Automatically Add New Contact Birthdays"
- Once the option above has been checked, when SimpleCalendar starts up again it will scan the list for a new Contact and if that Contact item has a 'Birth Date' field on it, they will be automatically added

**Comment by tibbi** [comment] 2021-02-23 15:08
duplicate of #906

**Closed by tibbi** 2021-02-23 15:08 UTC
Labels: feature request

**Comment by natrius** [comment] 2021-02-24 09:28
Don't wanna be annoying, but isn't it usally like: close the more recent one as duplicate? That would be #906 (4 Jun 2019) vs. this with 12 Sep 2018. Plus, this issue right here has already comments on it.

I mean, its your repo, do whatever you want, that was just a bit confusing :D

**Comment by tibbi** [comment] 2021-02-24 11:13
I prefer having the clearer issue, without having to read too much boilerplace
