### ISSUE TITLE
Notification schedule is not updated along with the event time

### ISSUE THREAD

**Issue by cos64** [SimpleMobileTools/Simple-Calendar#142] opened 2017-04-07 15:15 UTC
I created an event for 7:50. I meant it to be 7:50 AM, but I didn't pay enough attention and didn't realize it was defaulting to PM (That's probably because it was (yesterday) in the afternoon when I was scheduling the event). So the event got **scheduled for 7:50 PM**.
I asked for a **notification 2 hours earlier** (so at 5:50).
The day comes, the real-world event passes. I wonder why I didn't get a notification and why the event is still visible in the "Calendar event list" widget. Then I realize it was set for PM, so I change it to AM even though it had passed already - just to see whether it disappears from the event list (it did, that's OK). **Now the event is at 7:50 AM**.
Then, in the evening, **at 5:50 PM... I get the notification** ([screenshot](http://imgur.com/a/UyQje)).

Possibly related to #136 (or even duplicated, sorry if it is) - but I can't be sure without checking the code.

**Comment by tibbi** [comment] 2017-04-07 16:18
its a different issue, ill check it

**Comment by tibbi** [comment] 2017-04-09 19:16
can you reproduce it reliably? Because it seems to be working fine to me

**Comment by cos64** [comment] 2017-04-16 14:42
I just tried again and it reproduced:
- at 5:20, I set the alarm for 5:30, with reminder at start
- at 5:25, I moved the alarm to 5:20
- at 5:30, I got the notification

**Comment by tibbi** [comment] 2017-04-17 15:07
ye that explains it a lot clearer, it should be fixed in the next version. Thanks

**Closed** 2017-04-17 15:07 UTC
Labels: bug

**Comment by cos64** [comment] 2017-04-28 16:00
Verified and it works, thank you!
