### ISSUE TITLE
Default Reminders for Event Types

### ISSUE THREAD

**Issue by EliasKomar** [SimpleMobileTools/Simple-Calendar#1196] opened 2020-09-06 11:17 UTC
# The Idea
So it would be nice to be able to have default reminders for event types (e.g. always remind me of a birthday (event type) at 00:00 ) 

# Where it fits
This feature could be placed in Settings > Manage event types > Certain Event

There you could place an option called 'Default Reminder' or something alike with a slider to activate/deactivate and a dropdown menu which should look like the reminder settings at 'add a task' (you could probably just copy the code from there)

# Why you might want to implement this

Simple Calendar is a great calendar, which is well designed, has a lot of great features, while remaining simple. That's why I really love it. Implementing a feature like this would greatly improve the event types and with it the app.

**Comment by tibbi** [comment] 2020-09-06 14:09
a more generic way is using templates, so Im marking this at a duplicate of #566

**Closed by tibbi** 2020-09-06 14:09 UTC
