### ISSUE TITLE
[Feature] Add option to give each event it's own color.

### ISSUE THREAD

**Issue by Rexadev** [SimpleMobileTools/Simple-Calendar#1900] opened 2022-12-08 06:26 UTC
Maybe it's already been asked

**Comment by Aga-C** [comment] 2022-12-08 07:13
You can do this in Settings -> Manage event types.

**Comment by tibbi** [comment] 2022-12-08 08:11
duplicate of #360, thats where per-event colors will be added

**Closed by tibbi** 2022-12-08 08:11 UTC
