### ISSUE TITLE
Constant high CPU load

### ISSUE THREAD

**Issue by frainz-de** [SimpleMobileTools/Simple-Calendar#1523] opened 2021-10-27 09:28 UTC
Hi,

I have a similar situation as #1110, but as this was fixed in 6.13, I guess this is a new issue. I'm seeing a constant CPU usage by com.simplemobiletools.calendar.pro between 50% and 150% in top (via termux). In addition, com.android.providers.calendar and system_server also seem unusually high. I have some calendars synced with DavX5 and some with Etesync.
I suspect that something triggers sync too often, but I'm not sure about that.

I will send you the logcat logs via email as I'm not sure I can sanitize them enough for the open internet.

App version: 6.15.4
Android version: 8.0.0

**Comment by frainz-de** [comment] 2021-11-03 10:19
I didn't get the issue for a few days with caldav sync disabled entirely and also with it enabled but only for a single Etesync calendar. So I guess the issue is with DAVx5? But I'm not sure since the issue was so sporadic to begin with.

**Comment by jakobroehrl** [comment] 2021-11-03 12:41
I will test some days with another calender app and davx5

**Comment by michaelof** [comment] 2021-11-04 01:49
Same battery drain here. Nokia 7.1 and 7.2, latest F-Droid version 6.15.4.
Used with Nextcloud/calDAV, synched via DAVx5

**Comment by michaelof** [comment] 2021-11-17 15:25
@tibbi : As the Android system settings are saying that Simple Calender app and not davx5 is cosuming the cpu power, how can we test/narrow down the root cause? FYI in Apps / Apps usage Simple Calender is shown as #1 app,up to 20+% o a fully loaded battery. THis even with sync settings set to sync every 30 min for calendar entries. E.g. K9-Mail, where I have several IMAP PUSH connections in use for several email accounts, so permanently connected, just consumes 3%, in average

I've tried myself and set davx5 sync settings to "manual only", will report here if any change.

Somewhat painful issue, on both my wife's and my mobile ;)

**Comment by tibbi** [comment] 2021-11-17 16:32
Im not sure, it is apparently some CalDAV syncing related issue, like it happens too often. I dont have it on my devices though and actually not many people reported it, so it looks like something device or setup specific.

**Comment by nicolasGrim** [comment] 2021-11-17 19:01
Hi i'm having the same issue regarding battery usage on a oneplus nord ce, with the latest version on f-droid.
I also have DAVx5 and simple calendar working together, and the calendar uses at least 10 percent of a full battery.
Never tried Etesync so I'll give it a go and let you know.

**Comment by Tentos** [comment] 2021-11-21 18:29
I recently had a similar problem when updating to version 6.5.13 and 6.5.14: For unkonwn reasons, Simple Calendar started to synchronize my Caldav account every couple of seconds. I noticed this because this triggered a reload of the appointments in my custom ROM calendar app (i.e., the /e/OS Etar calendar fork), which shows a small notification during the calendar synchronization.

I do not have this problem with version 6.5.12. Unfortunately, I cannot tell what could have led to this strange bug, and whether it is ROM related. Maybe the others in this thread could try to downgrade/reinstall version 6.5.12 and see whether the CPU problem is still there?

**Comment by tibbi** [comment] 2021-11-21 18:34
Is that a typo or you really mean app versions like 6.5.13? Those are ancient ones.

**Comment by Tentos** [comment] 2021-11-21 18:44
(I hope to not have mixed up the version scheme or something similar...) Yes, I indeed mean versions 6.5.12-6.5.14.

- Version 6.5.12 (from 26 September 2021): regular synchronization in the set interval
- Version 6.5.13 (from 11 October 2021): synchronization every couple of seconds (reason unkown)
- Version 6.5.14 (from 14 October 2021): synchronzation every couple of seconds (reason unkown)

**Comment by michaelof** [comment] 2021-12-18 18:03
> Im not sure, it is apparently some CalDAV syncing related issue, like it happens too often.

Hi Tibbi, battery drain drops to <5% if DAVx5 option for calendar entries sync interval is set to "manual only". Nevertheless 5% for doing more or less nothing seems still too much :) Tried today with the newest SimpleCalendar version and DAVx5 sync settings set to "every 60 minutes" - 20% battery since last 100% charge, 15% left in total.

I haven't found the possibility in DAVx5 Github for issues, so opened a thread in their forum, FYI crosslinked: https://forums.bitfire.at/topic/2643/battery-drain-with-davx5-and-simplecalendar

Interesting for me is that SimpleContacts, using same Nextcloud account synced via same account in DAVx5, does NOT have this draining issue...

**Comment by michaelof** [comment] 2021-12-28 11:32
@tibbi there are answers in the DAVx5 forum, esp. this finding:
> So the system permanently starts DAVx5 with the information that something in the calendars has changed (“upload”). (Note that DAVx5 doesn’t start itself, but it is managed by the Android sync framework, which starts a sync when the content has changed). So I guess there’s really something changing the calendars/events permanently. But I don’t know the real cause.

As I'm using SimpleCalendar only, seems at first that SimpleCalendar must trigger this, somehow.

**Comment by tibbi** [comment] 2021-12-29 15:01
try the version mentioned at https://github.com/SimpleMobileTools/Simple-Calendar/issues/1037#issuecomment-1002636227 please, if it will still happen

**Comment by michaelof** [comment] 2021-12-30 10:55
@tibbi Android refuses to install mentioned version.
- downloaded apk.zip
- renamed, with SimpleFilemanager
- enabled SimpleFilemanager as trusted source for installs
- tried to install. looks normal at first, but last dialogue says: "App hasn't been installed" (translated from German)

any hints?

**Comment by Tentos** [comment] 2021-12-30 11:21
@michaelof Did you install Simple Calendar Pro from F-Droid? If yes, your current installation is signed by F-Droid while @tibbi's apk is signed by him. Android does not seem to allow an app update if the signatures differ.
Unfortunately, you have to uninstall your current installation first to install this new version.

Please note: If you want to revert to the old version afterwards, you will again to have uninstall Simple Calendar. Moreover, make sure that you have access to the apk of the old version. (I am currently stuck with 6.15.12, which is not available in F-Droid anymore. I have manually downloaded this version a couple of weeks ago to have a working version of Simple Calendar for the time being if I had to reinstall it.)

**Comment by michaelof** [comment] 2021-12-31 15:58
@Tentos thanks for your hint, installed yesterday after having uninstalled the other version.

@tibbi your suggested version solves the issue for me, SimpleCalendar now does not even show up in battery using app statistics, currently. What are your plans to merge this app version with the current trunk?

**Comment by Tentos** [comment] 2022-01-01 09:25
Unfortunately, the problem occurs with this version when I save an existing calendar entry on CalDAV. I have to force-stop the calendar app in the Android app info, and the frequent updates stop.

**Comment by michaelof** [comment] 2022-01-01 12:29
Confirmed :( As soon as you create a new event or update an existing event, the "Sending local deletes/updates to server” every minute starts again...

**Comment by tibbi** [comment] 2022-01-01 20:49
are you using Birthday adapter by any chance?

**Comment by michaelof** [comment] 2022-01-01 21:31
As I wasn't aware of this app until now, I just double checked: NO, not installed.

**Comment by tibbi** [comment] 2022-01-01 22:11
possible fix found, please check https://github.com/SimpleMobileTools/Simple-Calendar/issues/1037#issuecomment-1003627118

**Comment by Tentos** [comment] 2022-01-02 14:43
> possible fix found, please check [#1037 (comment)](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1037#issuecomment-1003627118)

This indeed seems to fix the problem. I have modified some calendar entries, and the frequent updates did not happen anymore. :)

**Comment by tibbi** [comment] 2022-01-02 16:04
okay, Ill close it then, let me know if it wont work in the new version 6.16.3. Thanks

**Closed by tibbi** 2022-01-02 16:04 UTC

**Comment by Tentos** [comment] 2022-01-16 20:20
I can confirm that the fix also works in Version 6.17.0 (in my case, the F-Droid build). Thank you for your work!
