### ISSUE TITLE
Treat Timezone Like Domestic Summer Clock Adjustment [Feature Request]

### ISSUE THREAD

**Issue by condemnedmeat** [SimpleMobileTools/Simple-Calendar#975] opened 2019-09-10 21:36 UTC
While in Western Europe I added a flight time to the calendar. Now I've moved one time zone east the flight time in the app has shifted with me one hour forward. I don't believe this issue exists when clocks move forward in Spring then back in Autumn does it? Does this mean the app is paying attention to time zone? When I make a calendar entry it's always made local time, wherever I've made it. Is there ever a time you wouldn't create an entry in local time? Shouldn't the app just disregard timezone?

**Comment by tibbi** [comment] 2019-09-11 06:27
timezone handling in general needs to be improved, duplicate of #436

**Closed by tibbi** 2019-09-11 06:27 UTC
