### ISSUE TITLE
Alarm uses notification sound not alarm sound

### ISSUE THREAD

**Issue by pager72** [SimpleMobileTools/Simple-Calendar#452] opened 2018-04-19 03:02 UTC
Currently Simple Calendar uses the notification sound and wrongfully says its the system wide alarm sound.

**Comment by tibbi** [comment] 2018-04-19 06:30
what app version do you have?

**Comment by pager72** [comment] 2018-04-19 06:34
3.4.2

**Comment by tibbi** [comment] 2018-05-02 18:29
I cannot reproduce it, what Android OS version do you have?

**Comment by tibbi** [comment] 2018-05-26 21:54
should be fixed in 4.0.4 which will start rolling out soon

**Closed by tibbi** 2018-05-26 21:54 UTC
Labels: bug
