### ISSUE TITLE
Added calendar entries disappear

### ISSUE THREAD

**Issue by mejo-** [SimpleMobileTools/Simple-Calendar#427] opened 2018-04-09 20:49 UTC
Since a few days (probably since the update from 3.3.x to 3.4.1), all calendar entries I add through Simple Calendar magically disappear after a few minutes. First, the new added entry appears in the calendar, then after a few minutes it vanishes.

My current wild guess is that new entries aren't added to the remote CalDAV calender and a background synchronization task overwrites the local calendar, removing the local-only calendar entry that had been created before. But that's totally uneducated, I didn't look into debugging this yet.

I'm running Simple Calendar 3.4.1 from F-Droid on a LineageOS 14.1 device and I use CalDAV calendars from a Nextcloud instance (synchronized via DAVdroid) as backend.

I didn't change anything in my setup recently, neither in the Calendar settings, nor in the DAVdroid settings. `CalDAV synchronization` is enabled in the Simple Calendar settings.

I'm happy to provide additional information it you give me further advice.

**Comment by mejo-** [comment] 2018-04-09 20:52
I just verified hat manually invoking `Update CalDAV calendar` (or whatever the exact english wording is) from the App menu makes the entries disappear.

**Comment by tibbi** [comment] 2018-04-12 21:04
I cannot reproduce it that easily. Are you online or offline when invoking the manual refresh?

**Comment by mejo-** [comment] 2018-04-13 08:52
Mh, for me that happens every single time I enter a date in Simple Calendar. I'm always online, both when creating and when refreshing.

**Comment by tibbi** [comment] 2018-04-13 08:58
Okay thanks, Ill try reproducing it with DavDroid and Nextcloud. I was trying only with Google Calendars, guess they handle it better.

**Comment by mejo-** [comment] 2018-04-13 09:14
If you want to, I can give you a Nextcloud account for testing purposes. Just email me at jonas at freesources dot org.

**Comment by tibbi** [comment] 2018-05-02 20:07
tried reproducing it with DAVDroid and Nextcloud but it always works properly :/ How about creating a new event and instead of pressing `Refresh CalDAV Calendar` you run a manual DAVDroid refresh? Do events get deleted?

**Comment by AeliusSaionji** [comment] 2018-05-14 12:11
Update 4.0 has caused many of my caldav entries to vanish, past and future.

**Comment by AeliusSaionji** [comment] 2018-05-14 12:15
Nevermind, this was a configuration issue with davdroid.

When "past event time limit" is 0, it apparently removes future events from the current day.

**Comment by AeliusSaionji** [comment] 2018-05-14 12:27
As far as I can tell Simple Calendar is working perfectly. Past versions must not have triggered sync properly, so I only bumped into this just now.

Thanks!

**Comment by tibbi** [comment] 2018-05-14 12:33
ye there were many caldav related fixes in version 4.0, so Ill close this one. Thanks

**Comment by mejo-** [comment] 2018-05-15 17:06
Unfortunately, I still have the same problem with version 4.0. I now did the following::

1. Create a calendar event in Simple Calendar. It's visible locally but not in the remote CalDAV calendar.
2. Ran a manual CalDAV sync in DAVdroid. Still the same: event is visible in Simple Calendar but not in the remote CalDAV calendar.
3. Waited a bit (~30m) in the hope that Simple Calendar pushed the event to the remote CalDAV calendar, without success.
4. Ran manual CalCAV calendar sync in Smple Calendar. Event disappeared from Simple Calendar and still not visible on remote CalDAV calendar.

I have "CalDAV synchronization" activated in Simple Calendar and the calendar is selected for CalDAV sync in DAVdroid. Also, other clients (Thunderbird) write successfully to the very same calendar with the same credentials, so I don't believe it's an issue with the CalDAV server (Nextcloud 13.0.2).

Do you have further suggestions on how to debug? Maybe try to catch a debug log using `adb`? I'd love to squash this bug as it currently renders Simple Calendar mostly unusable for me.

**Comment by tibbi** [comment] 2018-06-13 11:50
retry with 4.1.0 please, some related things have been improved

**Comment by mejo-** [comment] 2018-06-18 22:55
Hey @tibbi. Thanks for your great work on Simple Calendar. I upgraded to 4.1.0 now (since it hit F-Droid). Unfortunately the issue is still there.

**Comment by mejo-** [comment] 2018-06-23 10:09
Hey again. Today I finally tried another calendar app (Etar). This calendar doesn't suffer from the issue at all. Calendar entries are sucessfully synchronized to the remote CalDAV calendar and don't disappear even refreshing the CalDAV calendar.

Then I decided to go with a fresh reinstallation of your Simple Calendar app. I uninstalled it from my Smartphone and reinstalled it immediately afterwards. Great news: the issue disappeared. When I now enter a new calendar entry in Simple Calendar it as well gets synchronized to the remote CalDAV calendar, I can see it in all other CalDAV clients, and it doesn't disappear anymore after refreshing the CalDAV synchronization.

So I'm finally closing this bugreport. I'm still convinced that the issue is in Simple Calendar, but maybe some strange cornercase with an outdated internal database or whatever. For me, the issue is resolved after reinstallation.

**Comment by tibbi** [comment] 2018-06-23 10:40
Alright, not sure what could have gone wrong there :) Etar is the old stock calendar created by Google with a few minor tweaks, so it should be reliable indeed.

**Comment by NicoHood** [comment] 2019-03-02 16:15
Hi,
I recently also have the problem that random entries disappear. I restored a backup yesterday but today other meetings are lost again. That is supar annoying, especially because you do not exactly know which entries get deleted, you can only guess from what you remember.

I am using davx5 to syncronize with my radicale caldav server. The weird thing is, that none of all three components got any update within the last weeks.

Any ideas how to debug this? Can we somewhere check why an entry got deleted because of synchronization?

**Comment by tibbi** [comment] 2019-03-02 16:47
what app version do you have?

**Comment by NicoHood** [comment] 2019-03-02 17:17
6.3.1 from the playstore on the latest android 9 on an android one smartphone. Last update on 23.2.2019, maybe that introduced those issues? Could make sense.

**Comment by tibbi** [comment] 2019-03-03 10:41
not sure, does it work well via other android app calendars? Im not familiar with radicale server, so far nobody mentioned it

**Comment by AeliusSaionji** [comment] 2019-03-03 16:18
I use DavDroid (now DAVx5) to sync calendars and tasks hosted on Radicale. Everything seems to be fine with me.

**Comment by NicoHood** [comment] 2019-03-06 10:36
Well I did not try any other app. But what would it help? The entries are gone and synced back to the server. I dont know if its a failure on your side, davdroid or radicale. But I have backups and everything is in place again. I will come back if it happens again, but its possibly not even a problem of the calendar app.

**Comment by tibbi** [comment] 2019-03-06 10:51
the important part might be that who created the events. Is it Simple Calendar, some other app, or you create it on your PC or elsewhere? Thats what I would focus on at reproducing it.

**Comment by NicoHood** [comment] 2019-03-07 17:16
I create all events with your app. Also my phone is the only client that syncs against the server. I mainly use it as an automated backup in case I loose my phone, so I have all calendar entries on my pc.

**Comment by 7ocb** [comment] 2019-09-22 17:45
Also saw this recently a couple of times. I'm also using DAVx5 to synchronize.

**Comment by tibbi** [comment] 2020-02-06 20:19
someone retry with the latest 6.8.3 please, many things changed since the issue has been created.

**Closed** 2021-02-23 13:25 UTC
Labels: bug

**Comment by NicoHood** [comment] 2021-02-24 19:58
I had no problems the last year, so I guess it is fixed now.

**Comment by titibandit** [comment] 2024-04-08 17:22
Hey, that problem is happening right now on my (non-technicaly inclined) friend's phone.
I haven't tried to reinstall the app yet, maybe to give us a chance to figure out the problem's cause.
It's also when adding events to a calendar that's syncronized over caldav with the DAVx5 app.
The caldav server is whatever purelymail.com use for his caldav servers, but it seems that it's not related to the caldav server, looking at the history of this issue.
The app version is 6.23.1

**Comment by NuLL3rr0r** [comment] 2024-10-04 15:19
@titibandit I'm having the same issue with PurelyMail and the same setup. However, I have no idea how one can diagnose the root cause.

**Comment by titibandit** [comment] 2024-10-04 17:46
It's purelymail causing the problem. See https://github.com/ScottPeterJohnson/purelymail-issues/issues/222
