### ISSUE TITLE
Enhancement: reminder after ! start of event

### ISSUE THREAD

**Issue by Spielmops** [SimpleMobileTools/Simple-Calendar#578] opened 2018-08-10 20:52 UTC
For birthdays it is useful, if the calendar reminds me at that date some hours after ! start of the event. Eg. for my wifes birthday at 8:00 am, or for a friends birthday a 6:00 pm. 

Spielmops

**Comment by charBap** [comment] 2019-02-04 22:03
Can I work on this if it is available?

**Comment by tibbi** [comment] 2019-02-04 22:31
ye, but Im not yet sure how should it actually look like

**Comment by charBap** [comment] 2019-02-04 22:34
I was thinking just like the before option that it already available when creating events , add the after option too

**Comment by tibbi** [comment] 2019-02-04 22:38
ye something like that, but I dont want to flood the UI too much. Not many people need to trigger a reminder after the event started.

**Comment by charBap** [comment] 2019-02-04 22:40
Ok, I understand! Do you have any relatable issue in mind that needs to done @tibbi ??

**Comment by tibbi** [comment] 2019-02-04 22:54
you mean something related to this? Not really. Maybe showing reminders of missed events while the device was turned off needs to be done too.

**Comment by charBap** [comment] 2019-02-05 20:11
I could work on what you suggest. But I would need some help as I am new to android.

**Comment by tibbi** [comment] 2019-08-27 21:20
duplicate of #953

**Closed by tibbi** 2019-08-27 21:20 UTC
Labels: feature request

**Comment by Spielmops** [comment] 2020-03-08 08:41
One solution for this: custum time and the minus-sign before the numbers. The number-keyboard shows the sign, but I cannot insert it.
Spielmops
