### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Grossstadtkind** [SimpleMobileTools/Simple-Calendar#159] opened 2017-04-24 00:02 UTC
Feature request: Please add TODO entries, that means entries that remain visible e.g in the simple date-list view (or also in other views) until they are marked as "completed".

**Comment by tibbi** [comment] 2017-04-24 07:27
they will be added someday in the future, as "Tasks". So its a duplicate of #60

**Closed by tibbi** 2017-04-24 07:27 UTC
