### ISSUE TITLE
Maximum limit of concurrent alarms

### ISSUE THREAD

**Issue by dcasado** [SimpleMobileTools/Simple-Calendar#1134] opened 2020-05-04 18:26 UTC
Hi, I'm seeing this message when the calendar app synchronizes with CalDav. It appear sometimes during the day and when I do it manually. The strange thing is that with other calendar applications like Etar I haven't seeing it although I have the same calendars synchronized. I have calendars on [Etesync](https://www.etesync.com/) and also [Birthday Adapter](https://f-droid.org/en/packages/org.birthdayadapter/)

![Screenshot_20200504-094511_1](https://user-images.githubusercontent.com/10188511/80999267-a8d9fc80-8e44-11ea-9c7e-cabeb6103c11.jpg)

I have a OnePlus 6 with Paranoid Android Quartz 2 now but I also saw it with stock rom

**Comment by tibbi** [comment] 2020-05-04 18:50
duplicate of #1037 . And you definitely shouldnt be using Birthday Adapter, it is a heavily deprecated app from 2016. Maybe there wasnt such alarm limitations back then so they didnt care about spamming them.

**Closed by tibbi** 2020-05-04 18:50 UTC

**Comment by dcasado** [comment] 2020-05-05 07:57
I'm sorry I didn't found it. I will search for an alternative to birthday adapter and see if that annoying toast goes away.
Thanks!
