### ISSUE TITLE
better monthly view

### ISSUE THREAD

**Issue by azlux** [SimpleMobileTools/Simple-Calendar#266] opened 2017-11-06 14:16 UTC
Hi,
Just one feature for the next release.
When we create a 3 days event. The monthly view present this event like 3 event of 1 day. Is it simple to make a multiple day event having a better look, like one bar on the 3 day ?

Thank.

**Comment by tibbi** [comment] 2017-11-06 14:31
Hey, it isnt really simple so it wont be added in the next release yet, but I will take a look at it someday.

**Comment by tibbi** [comment] 2017-11-07 11:14
Ill actually close it as a duplicate of #173

**Closed by tibbi** 2017-11-07 11:14 UTC
Labels: feature request
