### ISSUE TITLE
Where can I change the color of each CalDAV calendar?

### ISSUE THREAD

**Issue by Usodiariom** [SimpleMobileTools/Simple-Calendar#1197] opened 2020-09-16 20:38 UTC
Hello, I've been with the application for a long time, but I can't find how to change the colors of each "Event".

The problem is that by default it places colors that do not conform to the CalDAV calendars and makes it impossible to see the black text in the dark gray rectangle.

Thanks for the info.

**Comment by tibbi** [comment] 2020-09-16 20:55
you cannot change colors on a per-event basis yet, only of a whole calendar. Duplicate of #360

**Closed by tibbi** 2020-09-16 20:55 UTC
