### ISSUE TITLE
Option to sync with local ICS file / sync with ICS link missing

### ISSUE THREAD

**Issue by tebe-nigrelli** [SimpleMobileTools/Simple-Calendar#2179] opened 2023-08-24 07:20 UTC
Syncing with ICS link is present in most calendar clients. At the moment, only a manual, one-time import is available.
Moreover, support for syncing with ICS files is a minimal change which would allow simple file syncing applications (eg. Syncthing) to communicate with Simple Calendar

**Comment by Aga-C** [comment] 2023-08-24 07:41
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/169.

**Closed** 2023-08-24 07:56 UTC
