### ISSUE TITLE
Events not displayed

### ISSUE THREAD

**Issue by torsten-scholer-healex** [SimpleMobileTools/Simple-Calendar#1424] opened 2021-07-27 09:05 UTC
I have a CalDav calendar with an event series where I declined 1 event of the series. Now the complete series is not displayed any more. However the underlying data should be correct as the Google Calendar displays all events correct and the Microsoft Calendar (original source) is also correct.

I guess Simple Calendar is removing all events due to the 1 declined event. 

Sadly this is a game breaker as I already missed an event due to this error!

**Comment by tibbi** [comment] 2021-07-27 13:26
what app version are you using?

**Comment by torsten-scholer-healex** [comment] 2021-07-28 07:51
I'm using v1.16.1 Pro

**Comment by tibbi** [comment] 2021-07-28 20:05
so can you reproduce it reliably like that? You create a repeating event, then you delete 1 instance in Google Calendar and after syncing it wont show up?

**Comment by hottehead** [comment] 2021-08-31 16:19
No I did not try to reproduce it. Currently the issue is gone. If this occurs again, what is the best way to extract the data so I can give you sample data to replicate?

**Comment by tibbi** [comment] 2021-08-31 16:36
well you can try exporting the given event into an .ics file by sharing it, maybe then I will be able to reproduce it. I cannot really fix such issues without reproducing. Anyway, Ill close this until it happens again or we can reproduce it somehow.

**Closed by tibbi** 2021-08-31 16:36 UTC
