### ISSUE TITLE
Slowness and collision in weekly and monthly views

### ISSUE THREAD

**Issue by llevrel** [SimpleMobileTools/Simple-Calendar#1815] opened 2022-08-24 16:06 UTC
Hi,

To see if the bugs I reported were corrected, I tried and installed 6.19.0. The weekly and monthly views are very slow. My phone is not very powerful, and it takes several seconds to display a month. Moreover, I saw event collision in weekly view (two overlapping frames, an all-day event and an all-day repeting event).

I'm back to 6.17.1 and don't see these problems. Probably something to do with the various improvements advertised in the release notes.

**Comment by tibbi** [comment] 2022-08-24 20:11
do you have events stored locally only or you use CalDAV sync?

**Comment by llevrel** [comment] 2022-08-25 07:09
I only use synched calendars. I use three accounts: one is synched via DAVx5 to my laptop (8 calendars), the second is Birthday adapter (1 cal), the third is my Google account (1 cal).

**Comment by tibbi** [comment] 2022-08-25 14:12
alright, Ill close it as a duplicate of #1468

**Closed by tibbi** 2022-08-25 14:12 UTC

**Comment by llevrel** [comment] 2022-08-25 16:58
> alright, Ill close it as a duplicate of #1468

I think not. That bug was submitted long ago about version 6.15.1 . Here I have no problem with that version, the slowness appeared all of a sudden between v6.17.1 and v6.19 . Also, I have no slowness in general, only to display the weekly or monthly view.
