### ISSUE TITLE
[Feature request] Adding an option to set the week start to Saturday

### ISSUE THREAD

**Issue by yshalsager** [SimpleMobileTools/Simple-Calendar#1267] opened 2021-01-18 18:23 UTC
Hi, thanks for the awesome apps you build for the community. You're doing an amazing job!

I'd like to suggest adding a new option to allow setting up the first day of the week as Saturday because many Middle East countries like Egypt use Saturday as the week start.

**Comment by tibbi** [comment] 2021-01-18 18:52
duplicate of #582

**Closed by tibbi** 2021-01-18 18:52 UTC
