### ISSUE TITLE
ICSdroid synchronization issue

### ISSUE THREAD

**Issue by bavay** [SimpleMobileTools/Simple-Calendar#640] opened 2018-09-26 14:08 UTC
I used to rely on icsdroid (through Davdroid) to synchronize a google calendar (a public one) to simple-calendar (that also has 3 other caldav calendars). Since around the summer, opening simple-calendar got very slow, changing from one month to the next is also very, very slow (I always use the month view). If I disable the ics calendar (and uninstall icsdroid), after forcing a few synchronizations everything is smooth again...

**Comment by bavay** [comment] 2018-09-26 14:17
Actually, it also seems that at each synchronization, the events are duplicated...

**Comment by bavay** [comment] 2018-09-26 14:54
Yes, it is very slow, it shows first an empty calendar and after several seconds you get the events (on a OnePlus3T)

**Comment by tibbi** [comment] 2018-09-26 18:27
do you have some really high amount of events in the calendar? Maybe some repeating daily?

**Comment by rfc2822** [comment] 2018-09-27 09:12
> Actually, it also seems that at each synchronization, the events are duplicated...

This should be fixed in ICSdroid 1.6… do you use 1.6?

**Comment by bavay** [comment] 2018-09-27 17:06
@tibbi: not such a large number of events, just a few meetings every few weeks (this is a team calendar only for team meetings, so quite light). 
@rcf2822: I was using ICSdroid from fdroid, but since I'm not sure if it was already version 1.6, I'll try installing it again and see how it goes... I'll let you know!

**Comment by bavay** [comment] 2018-10-01 14:37
I've now installed icsdroid 1.6, rebooted, waited a while (ie I went to sleep and left my phone to pull itself together) and now it works fine (ie it is smooth and switching to another month is almost instantaneous). The weird thing is that a few minutes after reinstalling icsdroid, everything was still very, very slow (something like 15 to 30 seconds to display a new month). Not doing anything, after rebooting and waiting, and voila, it works fine! I still had to delete duplicated events manually, though...

Anyway, sorry for "blaming" SimpleMobileTools for it and thanks for the suggestion to have a look at icsdroid! (by the way, even with DavDroid I still get some duplicates every now and then. Maybe a feature to automatically clean up duplicates in SimpleMobileTools could be useful...)

**Comment by tibbi** [comment] 2018-10-01 14:49
there are some sync issues that can cause duplicates, but so far I couldnt reproduce any, so couldnt fix it either. Hopefully Ill be able to fix it properly one day, I dont want to add cleanups.

**Comment by tibbi** [comment] 2018-11-06 21:18
note to self: might be reproducible with Tiny Calendar, more info in email from 6th november 2018 from alain.despatie

**Comment by bavay** [comment] 2018-11-08 16:21
If you could provide me with a version that could generate some detailed logs, I try to generate some logs for you... On my side, I have lots of duplicates (even one event that got duplicated 9 times!). This only happens with events created on an iPhone, synchronized to Nextcloud and back to my phone through Davdroid or for events coming from google calendar (through icsdroid). And the whole calendar gets very sluggish. Using LineageOS default calendar, there are no duplicates and the calendar is vastly more responsive (not even the smallest lag when browsing 6 months into the future when Simple-Calendar sometimes takes ~10 seconds to show a month or two into the future)

**Comment by tibbi** [comment] 2018-11-16 15:19
recheck with the pro version 6.0 released soon please

**Closed** 2018-11-16 17:53 UTC
Labels: bug
